hgsgtk article
golangtokyo/shoten6 pull request #1
Opened 2019-03-07 17:55 UTC by hgsgtk

2019-04-07 23:45 UTC, skanehira commented on articles/hgsgtk.re
> +//list[sampleTestHello][sample_test.go][go]{
go fmt掛けていないようなので書けておきましょう

2019-04-07 23:47 UTC, skanehira commented on articles/hgsgtk.re
> +なお、以降「テスト」と表記する場合、特に断りがない場合は「自動化されたユニットテスト」のことを指し示すと理解してください。
以降に「ユニットテスト」と「テスト」が混在しているので、統一しておきましょう

2019-04-07 23:48 UTC, skanehira commented on articles/hgsgtk.re
> +ここまでが、Goのユニットテストを作る上での基礎知識になります。基本的にはこれまで紹介した知識で最低限のテストコードを作成できるようになります。
この章に「ユニットテスト」と「テスト」が混在しているので、統一しておきましょう

2019-04-08 00:02 UTC, skanehira requested changes
気になるところコメントしました

2019-04-08 00:02 UTC, skanehira commented on articles/hgsgtk.re
> +作成したテストを先程紹介した @<code>{go test} で実行するとテストが通ることが確認できます。
全体「ユニットテスト」と「テスト」が混在しているので、統一しておきましょう

2019-04-08 00:02 UTC, skanehira commented on articles/hgsgtk.re
> +ユニットテストを書いている方であれば何かしらのメリットを感じて実践していることでしょうが、ユニットテストによって得られるメリットとしていくつかの「節約コスト」があります。一般的には次のような節約コストが挙げられます。
>実践していることでしょうが

「実践していると思いますが」のが柔らかくて丁寧な印象がありますがどうでしょうか？

2019-04-08 00:02 UTC, skanehira commented on articles/hgsgtk.re
> +** プログラムで実行可能な自動ユニットテストが準備されることで、手動でのユニットテストから開放されます。
>プログラムで実行可能な自動ユニットテストが準備されることで

「プログラムで実行可能な自動ユニットテストを準備することで」のが良い気がします

2019-04-08 00:02 UTC, skanehira commented on articles/hgsgtk.re
> +Goの特徴的な言語仕様として、 アサート（assertion） が提供されていない点が挙げられます。これは、@<href>{https://golang.org/doc/faq#assertions}にて理由が説明されていますが、「アサートが適切なエラーハンドリングとエラーレポートを考慮せずに済ますためのツールとして使われている」という経験上の懸念より提供されていません。適切なエラーハンドリング
>アサート（assertion） 

カッコ内に合わせるなら、アサーションが良いと思います

2019-04-08 00:02 UTC, skanehira commented on articles/hgsgtk.re
> +ユニットテストは維持するコストが発生すると「ユニットテストの考え方」にて説明しました。維持することを最小限にするためにもテストが失敗した際に「なぜ失敗したのか」について、それを見るプログラマに対してわかりやすい必要があります。そのため、適切なエラーレポートを行うことは非常に重要です。
>それを見るプログラマに対してわかりやすい必要があります。

「それを見るプログラマに対してわかりやすいレポートである必要があります。」でしょうか？

2019-04-08 00:02 UTC, skanehira commented on articles/hgsgtk.re
> +不安定なテスト（Fragile Test）が生まれてしまうことを避ける
他の箇所ではリストにしているので、ここも箇条書きをリストにしましょう

2019-04-08 00:02 UTC, skanehira commented on articles/hgsgtk.re
> +#@# xUTP
xUTPはなんですか？（所見でわかりませんでした）
脚注しておきましょう

2019-04-08 02:23 UTC, budougumi0617 reviewed
ざっくりみました。

2019-04-08 02:23 UTC, budougumi0617 commented on articles/hgsgtk.re
> +		t.Errorf("SayHello() = %#v, want %#v", got, want)
`string`なので`%s`で良いかも…

2019-04-08 02:23 UTC, budougumi0617 commented on articles/hgsgtk.re
> +-> % go test -v github.com/hgsgtk/go-snippets/testing-codes/sample
`->` ってなんでしょう？

2019-04-08 02:23 UTC, budougumi0617 commented on articles/hgsgtk.re
> +では、Goにおいて適切なエラーハンドリングを実現するためには、どのようにすればよいのでしょうか。Goでは testing パッケージが提供する @<code>{*T.Errorf}（@<code>{*T.Error}）・@<code>{*T.Fatalf}（@<code>{*T.Fatal}）というAPIが提供しています。それらを適切に使い分けることによって、適切なエラーハンドリングを実現します
このへん脚注にGoDocへのリンクほしい気がしますね。

2019-04-08 02:23 UTC, budougumi0617 commented on articles/hgsgtk.re
> +@<code>{*T.Errorf}では、「対象の関数は失敗した」と記録されますが、実行は継続されます。それに対して、@<code>{*T.Fatalf}では、@<code>{*T.Errorf}と同様に「対象の関数は失敗した」ことを記録しますが、同時に実行を停止し、次のテストケースの実行へと移ります。
> 対象の関数は失敗した

関数はテストケースをさしているんですかね？テスト対象を指しているのですかね？
どちらにしても「対象のテストケースが失敗した」のほうがいいかなと。（サブテスト使ったら”関数”は失敗しないですし。

2019-04-08 02:23 UTC, budougumi0617 commented on articles/hgsgtk.re
> +@<code>{*T.Errorf}では、「対象の関数は失敗した」と記録されますが、実行は継続されます。それに対して、@<code>{*T.Fatalf}では、@<code>{*T.Errorf}と同様に「対象の関数は失敗した」ことを記録しますが、同時に実行を停止し、次のテストケースの実行へと移ります。
> `@<code>{*T.Errorf}`

一応 `@<code>{*T.Error}/@<code>{*T.Errorf}`とかのほうがいいですかね（Fatalのほうも）

2019-04-08 02:23 UTC, budougumi0617 commented on articles/hgsgtk.re
> +@<list>{GetNum}を
WIP?

2019-04-08 02:23 UTC, budougumi0617 commented on articles/hgsgtk.re
> +ユニットテストにおいて致命的なエラーとして、テスト対象を実行・検証する前準備の処理の失敗が挙げられます。もしくは、例えば、http.Handlerをテストする際に擬似リクエストに失敗した場合、以降のテストを継続することができません。このような、処理継続が不可能なものに対してはテストをクラッシュさせることが効果的です。
> http.Handler

装飾忘れ

2019-04-08 02:23 UTC, budougumi0617 commented on articles/hgsgtk.re
> +一方、致命的ではないエラーとしては、複数観点での検証のひとつの検証が失敗したケースなどが挙げられます。この場合、検証失敗によって以降の処理継続が不可能になるわけではありません。よって、この場合はテストをクラッシュさせないことが効果的になるわけです。
> 処理継続が不可能

処理の継続？

2019-04-08 02:23 UTC, budougumi0617 commented on articles/hgsgtk.re
> +適切なエラーハンドリングを行うことによって、致命的ではないエラーである以上一回の実行で多くのエラーをプログラマはテストの失敗結果を得ることができます。適切なエラーハンドリングができていない例として次のようなテストコードが挙げられます。
> 適切なエラーハンドリングを行うことによって、致命的ではないエラーである以上一回の実行で多くのエラーをプログラマはテストの失敗結果を得ることができます。

ここちょっと意味がわかりませんでした。「致命的ではないエラーである以上、一回の実行で」って感じで読みますか？あと「多くのエラーを」がどこにかかっているのかわかりませんでした。
適切なエラーハンドリングを行うことによって、プログラマは一回の実行で多くのエラーをテストの失敗結果から知ることができます。って感じですか？前文で致命的ではないエラーの説明をしているのでもう一度この文でしなくてもいいかな。。（適切なエラーハンドリングにニュアンスが入っている気がする）

2019-04-08 02:23 UTC, budougumi0617 commented on articles/hgsgtk.re
> +適切なエラーハンドリングを行うことによって、致命的ではないエラーである以上一回の実行で多くのエラーをプログラマはテストの失敗結果を得ることができます。適切なエラーハンドリングができていない例として次のようなテストコードが挙げられます。
> 次のようなテストコード

参照で

2019-04-08 02:23 UTC, budougumi0617 commented on articles/hgsgtk.re
> +Goでは非常に広く使われているテストの技法として、表駆動（table-driven）テストというものがあります。例えば、次のようなテストコードになります。
wikiへのリンクですかね。
https://github.com/golang/go/wiki/TableDrivenTests

2019-04-08 02:23 UTC, budougumi0617 commented on articles/hgsgtk.re
> +Goでは非常に広く使われているテストの技法として、表駆動（table-driven）テストというものがあります。例えば、次のようなテストコードになります。
> 次のようなテストコード

ここも参照で

2019-04-08 02:23 UTC, budougumi0617 commented on articles/hgsgtk.re
> +テーブル駆動テストでは、必要に応じた新たな表の項目を追加するのが簡単であり、判定ロジックの複製の不要です。そのため、このテストに対して修正・追加したいプログラマの工数を最小限である維持コストの低いテストを実現する方法になります。合わせて、テストを読む際にも、対象関数のテストパターンが表にかかれているので可読性の高いドキュメンテーションとしての価値も高いテストとなります。
> 最小限である維持コストの低いテストを


「最小限である維持コスト」は使わない言い回しかも（であるの部分が）

2019-04-08 02:23 UTC, budougumi0617 commented on articles/hgsgtk.re
> +同一パッケージにした場合、privateな関数をテストすることができます。同一ではないパッケージにした場合は、他パッケージと同様の見え方になるので、実際の使用シーンを意識したテストケースになる利点があります。
ここの流れは `export_test`の説明を入れたいですね。
https://tech.mercari.com/entry/2018/08/08/080000

もしくはプログラミング言語Go、11.2.4を参照してください。

2019-04-08 02:37 UTC, hgsgtk commented on articles/hgsgtk.re
> +-> % go test -v github.com/hgsgtk/go-snippets/testing-codes/sample
すいません僕のbashのスタイリングが残ってました、、、！

2019-04-08 02:37 UTC, hgsgtk commented on articles/hgsgtk.re
> +-> % go test -v github.com/hgsgtk/go-snippets/testing-codes/sample
s/bash/zsh/

2019-04-08 02:43 UTC, hgsgtk commented on articles/hgsgtk.re
> +		t.Errorf("SayHello() = %#v, want %#v", got, want)
たしかに（雑にvしてたので小さな学びでした）

2019-04-08 03:03 UTC, hgsgtk commented on articles/hgsgtk.re
> +  // SayHelloの戻り値が期待値と異なる場合エラーとして処理する
なんでこうなるんだこれあとでなんかhookして変なことしてないかとかみるか・・・

2019-04-09 12:37 UTC, hgsgtk commented on articles/hgsgtk.re
> +ユニットテストを書いている方であれば何かしらのメリットを感じて実践していることでしょうが、ユニットテストによって得られるメリットとしていくつかの「節約コスト」があります。一般的には次のような節約コストが挙げられます。
この文章自体を消しました 🙇

2019-04-09 12:37 UTC, hgsgtk commented on articles/hgsgtk.re
> +** プログラムで実行可能な自動ユニットテストが準備されることで、手動でのユニットテストから開放されます。
この文章自体を消しました 🙇

2019-04-09 12:38 UTC, hgsgtk commented on articles/hgsgtk.re
> +不安定なテスト（Fragile Test）が生まれてしまうことを避ける
この章を諦めました（この章だけで１章くらい別にしてもいいくらいのボリュームがありそうだったので） 🙇

2019-04-09 12:40 UTC, hgsgtk commented on articles/hgsgtk.re
> +#@# xUTP
xUnit Test Patternsの書籍へのリンクを脚注してみました

https://github.com/golangtokyo/shoten6/pull/1/files#diff-95bf0899df4140d13fbea1d046bf039bR95

2019-04-09 12:40 UTC, hgsgtk commented on articles/hgsgtk.re
> +ユニットテストは維持するコストが発生すると「ユニットテストの考え方」にて説明しました。維持することを最小限にするためにもテストが失敗した際に「なぜ失敗したのか」について、それを見るプログラマに対してわかりやすい必要があります。そのため、適切なエラーレポートを行うことは非常に重要です。
たしかに！こちらで対応させてもらいました

https://github.com/golangtokyo/shoten6/pull/1/files#diff-95bf0899df4140d13fbea1d046bf039bR112

2019-04-09 12:41 UTC, hgsgtk commented on articles/hgsgtk.re
> +		t.Errorf("SayHello() = %#v, want %#v", got, want)
こちらで `%s` にしました。その他も型が分かってるものは型にあわせたフォーマットを指定しました

https://github.com/golangtokyo/shoten6/pull/1/files#diff-95bf0899df4140d13fbea1d046bf039bR56

2019-04-09 12:42 UTC, hgsgtk commented on articles/hgsgtk.re
> +では、Goにおいて適切なエラーハンドリングを実現するためには、どのようにすればよいのでしょうか。Goでは testing パッケージが提供する @<code>{*T.Errorf}（@<code>{*T.Error}）・@<code>{*T.Fatalf}（@<code>{*T.Fatal}）というAPIが提供しています。それらを適切に使い分けることによって、適切なエラーハンドリングを実現します
たしかに、脚注にGoDoc追加していきました

https://github.com/golangtokyo/shoten6/pull/1/files#diff-95bf0899df4140d13fbea1d046bf039bR187

2019-04-09 12:43 UTC, hgsgtk commented on articles/hgsgtk.re
> +@<code>{*T.Errorf}では、「対象の関数は失敗した」と記録されますが、実行は継続されます。それに対して、@<code>{*T.Fatalf}では、@<code>{*T.Errorf}と同様に「対象の関数は失敗した」ことを記録しますが、同時に実行を停止し、次のテストケースの実行へと移ります。
ありがとうございます！

```suggestion
@<code>{*T.Errorf}では、「対象のテストケースが失敗した」と記録されますが、実行は継続されます。それに対して、@<code>{*T.Fatalf}では、@<code>{*T.Errorf}と同様に「対象のテストケースが失敗した」ことを記録しますが、同時に実行を停止し、次のテストケースの実行へと移ります。
```

2019-04-09 12:44 UTC, hgsgtk commented on articles/hgsgtk.re
> +#@# cmpの紹介をcolumnでかく
[self review] cmpの紹介して！

2019-04-09 12:45 UTC, hgsgtk commented on articles/hgsgtk.re
> +
t.Helperを説明するなら、テストが失敗した際のエラー行について実際に失敗例があったほうが良さそう。

2019-04-09 12:46 UTC, hgsgtk commented on articles/hgsgtk.re
> +	tm := time.Date(2019, time.April, 14, 0, 0, 0, 0, testutil.GetJstLocation(t))
「具体的なこと」をやっているテストコードの量が減って、テストの可読性が上がりました。
テストの意味を伝える上で必要な情報にテストケース内のコードが集中できますね

的な説明を加える

2019-04-09 12:47 UTC, hgsgtk commented on articles/hgsgtk.re
> +
テストヘルパーを活用する上で「適切なエラーレポート」を疎かになるような共通化は逆にテストコードを良くしないので、気をつけよう

的な説明を加える

2019-04-09 12:56 UTC, hgsgtk commented on articles/hgsgtk.re
> +//list[goTestExecution][go testによるテスト実行][]{
cmdでよさそう

2019-04-09 12:56 UTC, hgsgtk commented on articles/hgsgtk.re
> +ひとつサンプルを見てましょう。"hello" と返却する@<code>{SayHello()}という関数があるとします。
"hello" これ hello でよさそう

2019-04-09 13:00 UTC, hgsgtk commented on articles/hgsgtk.re
> +このユニットテストの効果とコストの関係性について、『xUnit Test Patterns: Refactoring Test Code』@<fn>{xutpLink}という書籍では、「テストの経済性（Economics of Test Automation）」という言葉で説明されています。@<img>{hgsgtk-test-economical-graph}をご覧ください。
図がいい感じに当てはまるとは限らないから参照の仕方を考えたほうがよさそう

2019-04-09 13:02 UTC, hgsgtk commented on articles/hgsgtk.re
> +最初はユニットテストという新しい技術に対する学習・実践コストとして、ユニットテストのコストが嵩む時期が訪れます。しかし、じきにユニットテストに対する習熟や効率化により追加コストが落ち着いてくると、@<img>{hgsgtk-test-economical-graph}のように、ユニットテストがもたらす効果である節約コストと相殺されていきます。
最初とはどこ？
ソフトウェア開発から初めてテストを書き始める初期時点

とかの表現かな

2019-04-09 13:04 UTC, hgsgtk commented on articles/hgsgtk.re
> +ユニットテスト自体を維持するコストが発生する点について「費用対効果の高いユニットテストという考え方」にて説明しました。維持コストを最小限にするために意識するべき点のひとつとして、「適切なエラーレポート」という観点があります。テストが失敗した際に「なぜ失敗したのか」について、それを見るプログラマに対してわかりやすいレポートである必要があります。わかりやすいレポートにすることによって、テストの失敗に
ユニットテスト自体を維持するコストが発生する点について > 不自然、ユニットテスト自体の維持コストの最小化というところにつながればいいので文章を考えたほうがいい

2019-04-09 14:29 UTC, hgsgtk commented on articles/hgsgtk.re
> +ブラックボックステストは、「壊れやすいテスト（Fragile Test）」@<fn>{fragileTest}になりにくい利点があります。壊れやすいテストとは、動作コードの変更に敏感に反応してテストが落ちてしまうようなテストのことをいいます。ここでいう「敏感に」とは、外部への振る舞いを変えない内部の処理詳細の変更に対してもテストが落ちてしまうということです。変更検出（change detecte
ユニットテストが失敗する vs ユニットテストが落ちる

「ユニットテストが失敗する」に統一

2019-04-09 14:33 UTC, budougumi0617 commented on articles/hgsgtk.re
> +//footnote[xutpLink][https://www.amazon.co.jp/dp/0131495054/ref=cm_sw_r_tw_dp_U_x_Y8kJCb6EX02F6]
`https://amazon.jp/dp/0131495054`だけでダイジョブです。

2019-04-09 14:36 UTC, hgsgtk commented on articles/hgsgtk.re
> +//list[sampleTestHello][sample_test.go][go]{
`go fmt` かかったコードになりました

2019-04-09 14:36 UTC, hgsgtk commented on articles/hgsgtk.re
> +//footnote[xutpLink][https://www.amazon.co.jp/dp/0131495054/ref=cm_sw_r_tw_dp_U_x_Y8kJCb6EX02F6]
なるほど！
```suggestion
//footnote[xutpLink][https://www.amazon.co.jp/dp/0131495054]
```

2019-04-09 14:42 UTC, hgsgtk commented on articles/hgsgtk.re
> +ブラックボックステストは、「壊れやすいテスト（Fragile Test）」@<fn>{fragileTest}になりにくい利点があります。壊れやすいテストとは、動作コードの変更に敏感に反応してテストが落ちてしまうようなテストのことをいいます。ここでいう「敏感に」とは、外部への振る舞いを変えない内部の処理詳細の変更に対してもテストが落ちてしまうということです。変更検出（change detecte
https://github.com/golangtokyo/shoten6/pull/1/commits/7b3e18b97648758a0793f47b4d8231c3f387c68f

にてあわせて対応

2019-04-09 14:43 UTC, hgsgtk commented on articles/hgsgtk.re
> +ひとつサンプルを見てましょう。"hello" と返却する@<code>{SayHello()}という関数があるとします。
https://github.com/golangtokyo/shoten6/pull/1/commits/7b3e18b97648758a0793f47b4d8231c3f387c68f

にて対応

2019-04-09 14:44 UTC, hgsgtk commented on articles/hgsgtk.re
> +//list[goTestExecution][go testによるテスト実行][]{
`go testによるテスト実行`という表記が便利だったのでそのままにしておく

2019-04-09 14:59 UTC, hgsgtk commented on articles/hgsgtk.re
> +Goの特徴的な言語仕様として、 アサーションが提供されていない点が挙げられます。これは、@<href>{https://golang.org/doc/faq#assertions}にて理由が説明されていますが、「アサートが適切なエラーハンドリングとエラーレポートを考慮せずに済ますためのツールとして使われている」という経験上の懸念より提供されていません。適切なエラーハンドリングとはなんでしょうか。
公式FAQと表現してURLは脚注で示す

2019-04-09 15:00 UTC, hgsgtk commented on articles/hgsgtk.re
> +適切なエラーハンドリングについて、「致命的ではないエラーが発生した際にクラッシュさせずに処理を継続させることである」と説明されています。
改行いらなそう

2019-04-09 15:01 UTC, hgsgtk commented on articles/hgsgtk.re
> +では、適切なエラーレポートとはなんでしょうか。@<href>{https://golang.org/doc/faq#assertions}にて説明がありますが、直接的かつ適切な内容とされています。
公式FAQと表現してURLは脚注で示す

2019-04-09 15:25 UTC, hgsgtk commented on articles/hgsgtk.re
> +  // SayHelloの戻り値が期待値と異なる場合エラーとして処理する
fixed

2019-04-09 15:26 UTC, hgsgtk commented on articles/hgsgtk.re
> +Goでは非常に広く使われているテストの技法として、表駆動（table-driven）テストというものがあります。例えば、次のようなテストコードになります。
https://github.com/golangtokyo/shoten6/pull/1/commits/c516d981cb122d111b91eda4a2150c309d8c7e6b

I fixed mm

2019-04-09 16:09 UTC, hgsgtk commented on articles/hgsgtk.re
> +同一パッケージにした場合、privateな関数をテストすることができます。同一ではないパッケージにした場合は、他パッケージと同様の見え方になるので、実際の使用シーンを意識したテストケースになる利点があります。
https://github.com/golangtokyo/shoten6/pull/1/files#diff-95bf0899df4140d13fbea1d046bf039bR449

にてcolumn的に紹介してみました

2019-04-09 16:17 UTC, hgsgtk commented on articles/hgsgtk.re
> +Goでは非常に広く使われているテストの技法として、表駆動（table-driven）テストというものがあります。例えば、次のようなテストコードになります。
参照の意味の「次の」一層しました 🙇

2019-04-09 16:17 UTC, hgsgtk commented on articles/hgsgtk.re
> +適切なエラーハンドリングを行うことによって、致命的ではないエラーである以上一回の実行で多くのエラーをプログラマはテストの失敗結果を得ることができます。適切なエラーハンドリングができていない例として次のようなテストコードが挙げられます。
I fixed 
https://github.com/golangtokyo/shoten6/pull/1#discussion_r273573179

2019-04-09 16:20 UTC, hgsgtk commented on articles/hgsgtk.re
> +@<code>{*T.Errorf}では、「対象の関数は失敗した」と記録されますが、実行は継続されます。それに対して、@<code>{*T.Fatalf}では、@<code>{*T.Errorf}と同様に「対象の関数は失敗した」ことを記録しますが、同時に実行を停止し、次のテストケースの実行へと移ります。
そうしました！

https://github.com/golangtokyo/shoten6/pull/1/files#diff-95bf0899df4140d13fbea1d046bf039bR186

2019-04-09 16:20 UTC, hgsgtk commented on articles/hgsgtk.re
> +Goの特徴的な言語仕様として、 アサート（assertion） が提供されていない点が挙げられます。これは、@<href>{https://golang.org/doc/faq#assertions}にて理由が説明されていますが、「アサートが適切なエラーハンドリングとエラーレポートを考慮せずに済ますためのツールとして使われている」という経験上の懸念より提供されていません。適切なエラーハンドリング
"アサーション"にしました！

2019-04-09 16:21 UTC, hgsgtk commented on articles/hgsgtk.re
> +作成したテストを先程紹介した @<code>{go test} で実行するとテストが通ることが確認できます。
ユニットテスト・テストコードに統一しました。
（「壊れやすいテスト」など用語の都合上そのまま"テスト"と使っている箇所は残ってます。）

https://github.com/golangtokyo/shoten6/pull/1/commits/7b3e18b97648758a0793f47b4d8231c3f387c68f

2019-04-09 23:36 UTC, hgsgtk commented on articles/hgsgtk.re
> +最初はユニットテストという新しい技術に対する学習・実践コストとして、ユニットテストのコストが嵩む時期が訪れます。しかし、じきにユニットテストに対する習熟や効率化により追加コストが落ち着いてくると、@<img>{hgsgtk-test-economical-graph}のように、ユニットテストがもたらす効果である節約コストと相殺されていきます。
fixed

https://github.com/golangtokyo/shoten6/pull/1/commits/2333a0cd0172a35fe286d98233dc4bd569ae0cd1

2019-04-09 23:56 UTC, hgsgtk commented on articles/hgsgtk.re
> +ユニットテスト自体を維持するコストが発生する点について「費用対効果の高いユニットテストという考え方」にて説明しました。維持コストを最小限にするために意識するべき点のひとつとして、「適切なエラーレポート」という観点があります。テストが失敗した際に「なぜ失敗したのか」について、それを見るプログラマに対してわかりやすいレポートである必要があります。わかりやすいレポートにすることによって、テストの失敗に
fixed

https://github.com/golangtokyo/shoten6/pull/1/commits/7ec4809b57a7349429ab2aa31d5bc6053e0b5e3c

2019-04-09 23:57 UTC, hgsgtk commented on articles/hgsgtk.re
> +このユニットテストの効果とコストの関係性について、『xUnit Test Patterns: Refactoring Test Code』@<fn>{xutpLink}という書籍では、「テストの経済性（Economics of Test Automation）」という言葉で説明されています。@<img>{hgsgtk-test-economical-graph}をご覧ください。
fixed

2019-04-10 00:02 UTC, hgsgtk commented on articles/hgsgtk.re
> +テーブル駆動テストに加えて、サブテストを使うことができます。サブテストは@<code>{*T.Run}@<fn>{trun}を使用することによって実現します。@<list>{TestFizzBuzzGetMsgTableDriven}をサブテストを使うように書き換えます。
サブテストとはなにかについて説明する

2019-04-10 00:06 UTC, hgsgtk commented on articles/hgsgtk.re
> += 費用対効果の高いユニットテストを実現するためのGoのテスト基礎
タイトルがなんか、テストとユニットテストがあるのとそもそも冗長な気がする、ので考える

2019-04-10 00:18 UTC, hgsgtk commented on articles/hgsgtk.re
> +
エラーが発生した場合は、*testing.Tを渡して失敗させること、エラーを返さないことによってエラーチェックが不要になるので、"なにをテストしているのか"わかりやすいテストコードになる

的なことを加える

2019-04-10 00:32 UTC, hgsgtk commented on articles/hgsgtk.re
> +//list[sampleHello][sample.go][go]{
`sample.go`の部分を有意な説明文に変える

2019-04-10 00:44 UTC, hgsgtk commented on articles/hgsgtk.re
> +% go test -v github.com/hgsgtk/go-snippets/testing-codes/sample
突然 -v が出てきたので説明入れておく

2019-04-10 01:06 UTC, hgsgtk commented on articles/hgsgtk.re
> +% go test -v github.com/hgsgtk/go-snippets/testing-codes/sample
fixed

2019-04-10 01:06 UTC, hgsgtk commented on articles/hgsgtk.re
> +テーブル駆動テストに加えて、サブテストを使うことができます。サブテストは@<code>{*T.Run}@<fn>{trun}を使用することによって実現します。@<list>{TestFizzBuzzGetMsgTableDriven}をサブテストを使うように書き換えます。
fixed
https://github.com/golangtokyo/shoten6/pull/1/commits/eee7e908fc1a2c51e12a81fcaa3ddebc8453e993

2019-04-10 01:37 UTC, hgsgtk commented on articles/hgsgtk.re
> +	tm := time.Date(2019, time.April, 14, 0, 0, 0, 0, testutil.GetJstLocation(t))
fixed

https://github.com/golangtokyo/shoten6/pull/1/commits/520cd7661aa24b4f80e24f69e7d48e1e77c5e1ec

2019-04-10 01:37 UTC, hgsgtk commented on articles/hgsgtk.re
> +
fixed

https://github.com/golangtokyo/shoten6/pull/1/commits/520cd7661aa24b4f80e24f69e7d48e1e77c5e1ec

2019-04-10 01:38 UTC, hgsgtk commented on articles/hgsgtk.re
> +
> テストが失敗した際のエラー行
まぁこれはいいや

2019-04-10 03:42 UTC, hgsgtk commented on articles/hgsgtk.re
> +本章で扱う"ユニットテスト"という言葉について予め定義しておきます。ユニットテストとは、関数やメソッドレベルでの動作保証を行うテストです。ユニットテストを行う手段として手動によるユニットテスト・自動化されたユニットテストの２種類があります。手動によるユニットテストとは、事前に用意したユニットテスト仕様書をもとに人間の手によって行われるユニットテストです。本章では、自動化されたユニットテストを扱い
```suggestion
本章で扱う"ユニットテスト"という言葉について予め定義しておきます。ユニットテストとは、関数やメソッドレベルでの動作保証を行うテストです。ユニットテストを行う手段として手動によるユニットテスト・自動化されたユニットテストの２種類があります。手動によるユニットテストとは、事前に用意したユニットテスト仕様書をもとに人間の手によって行われるユニットテストです。対照的に、自動化されたユニットテストでは、プログラムにより実行可能なテストコードを作成し、それを実行します。本章で扱うのは自動化されたユニットテストですので、"テストコードをどのように書いていくか"という点について焦点をあてて進めていきます。
```

2019-04-10 04:31 UTC, hgsgtk commented on articles/hgsgtk.re
> +では、適切なエラーレポートとはなんでしょうか。Goの公式FAQの"Why does Go not have assertions?"@<fn>{goFaqAssertions}では、直接的かつ適切な内容と説明されています。
引用っぽく

```suggestion
では、適切なエラーレポートとはなんでしょうか。Goの公式FAQの"Why does Go not have assertions?"@<fn>{goFaqAssertions}では、"直接的かつ適切な内容"と説明されています。
```

2019-04-10 05:54 UTC, hgsgtk commented on articles/hgsgtk.re
> +//list[GetNum][受け取った文字列を数値に変換して返すGetNum()][go]{
"ユニットテストにおいて致命的なエラーとして、テスト対象を実行・検証する前準備の処理の失敗が挙げられます。このような、処理の継続が不可能なものに対してはユニットテストをクラッシュさせることが効果的です。"

に合致したコード例に変える

2019-04-10 08:04 UTC, hgsgtk commented on articles/hgsgtk.re
> +
ライブラリの話にまではそこまで吹き込んでないので割愛

2019-04-10 08:14 UTC, hgsgtk commented on articles/hgsgtk.re
> +//list[GetNum][受け取った文字列を数値に変換して返すGetNum()][go]{
https://github.com/golangtokyo/shoten6/pull/1/commits/f989ac91d4159b501a85d01ee4500fcd89306a68

I fixed

2019-04-10 08:15 UTC, hgsgtk commented on articles/hgsgtk.re
> +//list[sampleHello][sample.go][go]{
fixed

2019-04-10 08:15 UTC, hgsgtk commented on articles/hgsgtk.re
> += 費用対効果の高いユニットテストを実現するためのGoのテスト基礎
fixed

2019-04-10 10:01 UTC, budougumi0617 reviewed
時間ないのであとはシングルコメントでつけてきますね。

2019-04-10 10:01 UTC, budougumi0617 commented on articles/hgsgtk.re
> +//footnote[gotestcmd][@<href>{https://golang.org/pkg/cmd/go/internal/test/}]
`go test`コマンドにリンクするならこっちじゃないですかね。
https://golang.org/pkg/cmd/go/#hdr-Test_packages

2019-04-10 10:06 UTC, hgsgtk commented on articles/hgsgtk.re
> +//footnote[gotestcmd][@<href>{https://golang.org/pkg/cmd/go/internal/test/}]
```suggestion
//footnote[gotestcmd][@<href>{https://golang.org/pkg/cmd/go/#hdr-Test_packages}]
```

hai!

2019-04-10 10:11 UTC, budougumi0617 commented on articles/hgsgtk.re
> +package sample_test
直さなくてもいいですが、説明してない `_test`使っている

2019-04-10 10:12 UTC, hgsgtk commented on articles/hgsgtk.re
> +package sample_test
たしかに、ここでは同一パッケージにしますかねぇ（序盤の制約が難しいポイントですよね。。。）

2019-04-10 10:15 UTC, budougumi0617 commented on articles/hgsgtk.re
> +% go test -v sample
私がzsh使ってるとか別の理由なのかな。`go test -v ./sample`とか書かず、この書きかたで書いても実行できます？
```
$ go test sample
can't load package: package app: cannot find package "sample" in any of:
	/usr/local/opt/go/libexec/src/sample (from $GOROOT)
	/Users/budougumi0617/go/src/sample (from $GOPATH)
```

まあ普通に `${GOPATH}/src/sample`と思えばいいのかな。

2019-04-10 10:16 UTC, hgsgtk commented on articles/hgsgtk.re
> +% go test -v sample
`${GOPATH}/src/sample`の解釈でしたね。。。実行できるように相対パスにします・・・

2019-04-10 10:16 UTC, budougumi0617 commented on articles/hgsgtk.re
> +% go test -v sample
でもコードみると `${GOPATH}/src/github.com/hgsgtk/go-snippets/testing-codes/sample`にある気がする。

2019-04-10 10:20 UTC, hgsgtk commented on articles/hgsgtk.re
> +package sample_test
変更箇所が多かったので最初の方で _testは後で説明するよって書くようにします。。。

2019-04-10 10:25 UTC, hgsgtk commented on articles/hgsgtk.re
> +% go test -v sample
すごくよしなに読みっとてくれ感がただよってしまっていたので、`go test ./sample`などに書き換えました 🙇 

https://github.com/golangtokyo/shoten6/pull/1/commits/445c1fcd9d0ab7e87810ca551470fa1a6cdeb9f6

2019-04-10 10:26 UTC, hgsgtk commented on articles/hgsgtk.re
> +package sample_test
"外部テストパッケージ"で説明するよっていう一文を加えました 

https://github.com/golangtokyo/shoten6/pull/1/commits/445c1fcd9d0ab7e87810ca551470fa1a6cdeb9f6

2019-04-10 10:27 UTC, budougumi0617 commented on articles/hgsgtk.re
> +ユニットテスト自体のコストの発生について"費用対効果の高いユニットテストとは"にて説明しました。発生するコストのひとつであるユニットテストの維持コストを最小限におさえるためには、適切なエラーレポートを意識する必要があります。
> "費用対効果の高いユニットテストとは"にて説明しました。


参照使えませんでしたっけ。( `@<hd>`)
https://github.com/kmuto/review/blob/master/doc/format.ja.md#%E8%A6%8B%E5%87%BA%E3%81%97%E5%8F%82%E7%85%A7

2019-04-10 10:28 UTC, hgsgtk commented on articles/hgsgtk.re
> +ユニットテスト自体のコストの発生について"費用対効果の高いユニットテストとは"にて説明しました。発生するコストのひとつであるユニットテストの維持コストを最小限におさえるためには、適切なエラーレポートを意識する必要があります。
えっそんな技が！

2019-04-10 10:37 UTC, hgsgtk commented on articles/hgsgtk.re
> +ユニットテスト自体のコストの発生について"費用対効果の高いユニットテストとは"にて説明しました。発生するコストのひとつであるユニットテストの維持コストを最小限におさえるためには、適切なエラーレポートを意識する必要があります。
参照対応しました

https://github.com/golangtokyo/shoten6/pull/1/commits/9e9bb9a1c6f097b1d4e82c0142930660fdcfc301

2019-04-10 10:38 UTC, hgsgtk commented on articles/hgsgtk.re
> +package sample_test
参照対応しました

https://github.com/golangtokyo/shoten6/pull/1/commits/9e9bb9a1c6f097b1d4e82c0142930660fdcfc301

2019-04-10 10:57 UTC, budougumi0617 commented on articles/hgsgtk.re
> +	tm := time.Date(2019, time.April, 14, 0, 0, 0, 0, testutil.GetJstLocation(t))
ここ微妙にはみ出てそうです。
<img width="792" alt="スクリーンショット 2019-04-10 19 57 12" src="https://user-images.githubusercontent.com/1883265/55873551-ea10c600-5bca-11e9-8180-008637739b8b.png">

2019-04-10 11:00 UTC, budougumi0617 commented on articles/hgsgtk.re
> +テストコードを置くパッケージについて２つの選択肢があります。テスト対象と同一のパッケージにするか、外部テストパッケージにする２つの選択肢です。外部テストパッケージは、@<code>{xxx_test}の形式のパッケージ名になり、たとえば sample パッケージであれば sample_test というパッケージ名です。
> 外部テストパッケージは、@<code>{xxx_test}の形式のパッケージ名になり、たとえば sample パッケージであれば sample_test というパッケージ名です。

ここ同じpkg名なのに片方が装飾されていてのこりの2つはそのままですね。統一したい。
今までの文中のpkgの書き方も合わせて、統一がラクなほう（装飾する/しない）に合わせちゃったほうが良さそう。

2019-04-10 11:04 UTC, budougumi0617 commented on articles/hgsgtk.re
> +テストパッケージをどちらにするのかはこれらのどちらの利点を重視するかによって変わるでしょう。筆者は、壊れやすいテスト発生による維持コストの増加の懸念とパッケージのクライアントの視点の２つの利点を重視するケースが多いです。そのため、ブラックボックステストのなりやすい外部テストパッケージにテストコードを置くようにしています。そのうえで、非公開機能に対して公開機能を介さずに直接ユニットテストを書きたい
```suggestion
テストパッケージをどちらにするのかはこれらのどちらの利点を重視するかによって変わるでしょう。筆者は、壊れやすいテスト発生による維持コストの増加の懸念とパッケージのクライアントの視点の２つの利点を重視するケースが多いです。そのため、ブラックボックステストになりやすい外部テストパッケージとしてテストコードを置くようにしています。そのうえで、非公開機能に対して公開機能を介さずに直接ユニットテストを書きたい場合には、非公開機能を別パッケージの公開機能として切り出せないか検討する方針としています。
```

ブラックボックステスト **に** なりやすい外部テストパッケージ **として** ...？

2019-04-10 11:05 UTC, hgsgtk commented on articles/hgsgtk.re
> +	tm := time.Date(2019, time.April, 14, 0, 0, 0, 0, testutil.GetJstLocation(t))
ありがとうございます、修正しました 🙇 

https://github.com/golangtokyo/shoten6/pull/1/commits/6561e16ffc75f8e410ceefd2846cc0ae9c4f40c9

<img width="449" alt="Screen Shot 2019-04-10 at 20 05 03" src="https://user-images.githubusercontent.com/8839280/55873958-f34e6280-5bcb-11e9-8503-d13cdd541ad2.png">

2019-04-10 11:12 UTC, hgsgtk commented on articles/hgsgtk.re
> +テストコードを置くパッケージについて２つの選択肢があります。テスト対象と同一のパッケージにするか、外部テストパッケージにする２つの選択肢です。外部テストパッケージは、@<code>{xxx_test}の形式のパッケージ名になり、たとえば sample パッケージであれば sample_test というパッケージ名です。
装飾しない側で統制してみました

https://github.com/golangtokyo/shoten6/pull/1/commits/7004f2cea9159ff61e1f5e88894499deaf8c2dc9

2019-04-10 11:16 UTC, hgsgtk commented on articles/hgsgtk.re
> +テーブル駆動テストでは、必要に応じた新たな表の項目を追加するのが簡単であり、判定ロジックの複製の不要です。そのため、テストコードに対する修正・追加コストの低いユニットテストを実現する方法になります。あわせて、テストコードを読む際にも、対象関数のテストパターンが表にかかれているので可読性の高いユニットテストとなります。さらに、判定ロジックの複製が不要な分、適切なエラーレポート・エラーハンドリングに
```suggestion
テーブル駆動テストでは、必要に応じた新たな表の項目を追加するのが簡単であり、判定ロジックの複製が不要です。そのため、テストコードに対する修正・追加コストの低いユニットテストを実現する方法になります。あわせて、テストコードを読む際にも、対象関数のテストパターンが表にかかれているので可読性の高いユニットテストとなります。さらに、判定ロジックの複製が不要な分、適切なエラーレポート・エラーハンドリングに集中することができます。
```

fix

2019-04-10 11:28 UTC, budougumi0617 approved these changes
LGTM

2019-04-10 11:28 UTC, merged