po3rinの執筆内容の追加
golangtokyo/shoten6 pull request #2
Opened 2019-03-21 16:08 UTC by po3rin

## What
po3rinの執筆内容「Goで始める画像処理&画像解析」の本文です。

## ToDo
- [ ] より良い実装の追求。。。
- [ ] Goの公式ブログから引用されている画像を差し替える？？
- [ ] 乃木坂の画像は多分使えないので差し替え(確実)

2019-03-31 01:33 UTC, budougumi0617 reviewed
ちょっと時間切れしてしまったのでひとまずここまでで。

2019-03-31 01:33 UTC, budougumi0617 commented on articles/po3rin.re
> +初めましてpo3rinです。業務ではGo言語をメインに使って開発しています。この章ではGoによる画像処理&画像解析の方法を紹介します。最初は入門から始まり、中盤からは様々な画像処理のTipsを紹介します。終盤では更に突っ込んでOpenCVを使った顔認識や輪郭抽出などの方法を紹介します。初めての方でもこの章を読み終える頃には、Goでエレガントに画像を扱えるようになっていることでしょう。ソースコード
> 最初は入門から始まり、中盤からは様々な画像処理のTipsを紹介します。終盤では更に突っ込んで

節にも参照貼れるので、 `X.X節からは様々な画像処理のTipsを…`のようにしたほうがいいかもしれませんね。

2019-03-31 01:33 UTC, budougumi0617 commented on articles/po3rin.re
> +初めましてpo3rinです。業務ではGo言語をメインに使って開発しています。この章ではGoによる画像処理&画像解析の方法を紹介します。最初は入門から始まり、中盤からは様々な画像処理のTipsを紹介します。終盤では更に突っ込んでOpenCVを使った顔認識や輪郭抽出などの方法を紹介します。初めての方でもこの章を読み終える頃には、Goでエレガントに画像を扱えるようになっていることでしょう。ソースコード
> 最初は入門から始まり、中盤からは様々な画像処理のTipsを紹介します。終盤では更に突っ込んで

三部構成になっているならば、章の構成も以下のようにしたほうがいいかもしれないですね

- 3.1 入門
  - 3.1.1 imageパッケージの基本を抑えよう
  ...
- 3.2 Tips
  ...
- 3.3 OpenCVなどを使った応用
  ...

2019-03-31 01:33 UTC, budougumi0617 commented on articles/po3rin.re
> +今回、@tottieさんのGopher@<fn>{gopher}くんのイラストの利用許可を頂きました。@<img>{po3rin-tottie-gopher}などの素敵なイラストを描いている方です。是非Twitter等で検索してみて下さい。
脚注でtwitterアカウントのURLを貼っておけばよいのでは。

2019-03-31 01:33 UTC, budougumi0617 commented on articles/po3rin.re
> +また、今回の章で使用するダウンロードデータを皆さんが金銭の発生する二次利用として利用してしまうと法律的にアウトなのでご了承ください。
ちなみになんですが、技術書典も「金銭の発生する二次利用（一次利用になっている？）」ですがだいじょぶですよね？

2019-03-31 01:33 UTC, budougumi0617 commented on articles/po3rin.re
> +また、今回の章で使用するダウンロードデータを皆さんが金銭の発生する二次利用として利用してしまうと法律的にアウトなのでご了承ください。
法律的にアウトって具体的にどういうことですか？金銭が発生しなければ二次利用OKですか？

権利周りの話をするならばCCライセンス、BSDやMITのライセンスといった該当するライセンス名を明記したほうがいいかと。（独自の契約ならば条件を書く）
@tottieさんとはどのライセンスで利用許諾いただいてるんでしょうか。

2019-03-31 01:33 UTC, budougumi0617 commented on articles/po3rin.re
> +まずはGoで画像を扱う際の中心になるimageパッケージの基本を押さえましょう。このタイミングで@tottieさんのGopherくんのイラスト(@<img>{po3rin-tottie-gopher})をダウンロードしておいてください。
”基本を抑える”ですか？”基本を押さえる”ですか？統一したほうがいいですね。

調べると知恵袋とかブログは「基本を押さえる」派が多そうですが、goo国語辞書的には「基本を抑える」っぽい。。。

2019-03-31 01:33 UTC, budougumi0617 commented on articles/po3rin.re
> +//list[download_gopher][可愛いGopherくんの画像をローカルに落とす][]{
「落とす」でも通じますが、上で「ダウンロードしておいてください。」と書いているならば「ダウンロードする」ですかね。使う用語は統一しましょう。

2019-03-31 01:33 UTC, budougumi0617 commented on articles/po3rin.re
> +まずは画像ファイルを@<code>{image.Image}の型に変換して画像のデータをみてみましょう。
`image.Image`ってインターフェースなので、「型」って言われるとなにか違和感が…

2019-03-31 01:33 UTC, budougumi0617 commented on articles/po3rin.re
> +@<list>{getimg}では@<code>{png.Decode}で標準入力を@<code>{image.Image}型にデコードしています。@<list>{getimg}を@<list>{rungo}のように実行すると画像の縦横の長さや、色についての情報が確認出来ます。
`@<code>{png.Decode}` 関数

読むだけだと`@<code>{XXXX} `が型なのか？変数なのか？関数なのか？メソッドなのか？わからないので、名前のあとに補足的に書いたほうがいいです。

2019-03-31 01:33 UTC, budougumi0617 commented on articles/po3rin.re
> +RGBAとは、ディスプレイ画面で色を表現するために用いられる、赤（Red）、緑（Green）、青（Blue）の3色に、アルファ（Alpha）と呼ばれる透過度の情報を加えたもののです。RGBチャンネルにアルファ値が乗算されている形式をPre-multiplied Alpha(乗算済みアルファ)、乗算されていない形式をStraight Alphaと呼びます。Goのimage/colorパッケージでは
> Goのimage/colorパッケージでは、NRGBAはStraight Alphaを表現しています。

文脈的に
- Goのimage/colorパッケージでは、Straight AlphaをNRGBA構造体として表現しています。 
- Goのimage/colorパッケージでは、Straight AlphaをNRGBA構造体で表現しています。 
とかですかねえ

2019-03-31 01:33 UTC, budougumi0617 commented on articles/po3rin.re
> +@<code>{image.Image}の実装を@<list>{image_Image}でみてみましょう。今回使った3つのメソッドを持つインターフェースになっています。先ほど確認したように、それぞれのメソッドは画像の基本的な情報を返します。
> `@<code>{image.Image}`の実装を


ここも上と一緒で、インターフェースの実装というのはちょっと変な気がするので、`@<code>{image.Image}インターフェースの定義を`って書くべきですかね。

2019-03-31 01:33 UTC, budougumi0617 commented on articles/po3rin.re
> +Goではpng,jpeg,gifの画像フォーマットが標準パッケージでサポートされています。1点注意があり、画像フォーマットのパッケージの関数などを使わない場合でも@<code>{import _ image/png}のようにブランクインポートで対応するを読み込んでおかないと実行時にエラーが発生します。理由を探る為に@<code>{image/png/reader.go}をみてみましょう。
> のようにブランクインポートで対応するを読み込んでおかないと実行時にエラーが発生します。

対応するを読み込んでおかないと が日本語として変ですね。

2019-03-31 01:33 UTC, budougumi0617 commented on articles/po3rin.re
> +@<list>{image_register}のようにinit関数で使える画像フォーマットをパッケージ内のinit関数@<fn>{init}内で登録しています。その為、init関数を発火させる為にブランクインポートをする必要があります。
> init関数で使える画像フォーマットをパッケージ内のinit関数@<fn>{init}内で登録しています。


脚注するときは初出の場所につけ増すね（でも最初の"init関数"はないほうが文として正しい気もしますが）

ついでにinitも`@<code>`しておくべきでは。

2019-03-31 01:33 UTC, budougumi0617 commented on articles/po3rin.re
> +	// 受け取った画像と同じ大きさのカラーモードGray16の画像を生成.
ここだけ句点が「.」

2019-03-31 01:33 UTC, budougumi0617 commented on articles/po3rin.re
> +@<list>{grayscale}の通り、Goで画像加工をする際には、まず目的の画像(dstと呼ぶ)を作成し、元画像(srcと呼ぶ)から1画素ずつ処理してdstにセットするという流れになります。今回においてはsrcから1画素値づつ所得し、その色をグレースケール化してdstにセットしています。濃淡加工やセピア加工などのエフェクト処理においてもこのフローは鉄板なので覚えておきましょう。
dst などに`@code`装飾忘れてます。

2019-03-31 01:33 UTC, budougumi0617 commented on articles/po3rin.re
> +@<list>{grayscale}の通り、Goで画像加工をする際には、まず目的の画像(dstと呼ぶ)を作成し、元画像(srcと呼ぶ)から1画素ずつ処理してdstにセットするという流れになります。今回においてはsrcから1画素値づつ所得し、その色をグレースケール化してdstにセットしています。濃淡加工やセピア加工などのエフェクト処理においてもこのフローは鉄板なので覚えておきましょう。
コードコメント中は「1ピクセル」、ここでは「1画素」。単位の呼び方は統一したほうがいいです。

2019-03-31 01:33 UTC, budougumi0617 commented on articles/po3rin.re
> +	n := (1.0-b)*(1.0-a)*f(ps[0].X, ps[0].Y) +
`n`の宣言不要では

2019-03-31 01:33 UTC, budougumi0617 commented on articles/po3rin.re
> +今回はコードを追いやすいようにシンプルな形でパッケージを作りました。Lerpの式はLerp関数で実装しています。引数に関数@<m>{f}、@<m>{\alpha}、@<m>{\beta}、近傍4画素の位置だけ渡せば実行できるのがわかります。
> Lerp関数

装飾忘れ

2019-03-31 01:33 UTC, budougumi0617 commented on articles/po3rin.re
> +func Lerp(f PosDependFunc, a float64, b float64, ps Points) float64 {
私は`f PosDependFunc, a, b float64, ps Points` って書いちゃう派ですね

2019-03-31 01:33 UTC, budougumi0617 commented on articles/po3rin.re
> +また、今回の章で使用するダウンロードデータを皆さんが金銭の発生する二次利用として利用してしまうと法律的にアウトなのでご了承ください。
Goオフィシャルロゴもあった。オフィシャルロゴって金銭発生するところで使うとアウトなんでしたっけ。。。？
画像によって権利関係が違うならば個別にそれぞれの条件を書いたほうがいいかと。

2019-03-31 01:33 UTC, budougumi0617 commented on articles/po3rin.re
> +今回、画像の合成においては@<img>{po3rin-synthesis-flow}のようなフローを踏みます。背景画像にマスクをかけてdstに合成し、Goのロゴをその上からdstに合成します。矢印に紐づいている関数の意味は後ほど説明します。
dst 装飾忘れ

2019-03-31 01:33 UTC, budougumi0617 commented on articles/po3rin.re
> +では必要な素材を準備する関数を作りましょう。必要なのはsrc(Goのロゴ)とcover(背景画像)とmask(背景画像をマスキングする画像)とdst(合成を受ける画像)です。画像はそれぞれOGP画像の大きさに合うように前節で実装したリサイズ関数を使いましょう。前節の実装を飛ばした方は、@<code>{github.com/po3rin/resize}パッケージとして全く同じリサイズ機能を提供する
この辺も装飾必要ですかね。

2019-03-31 01:33 UTC, budougumi0617 commented on articles/po3rin.re
> +// getLerpParam 1軸に対して、Lerpで使うパラメータと近傍点をdstの座標と拡大縮小比率から所得する関数
コードコメントに句点をつけるときとつけないときが混ざっているので表記を統一してください。
私は句点つける派かなあ

2019-03-31 01:33 UTC, budougumi0617 commented on articles/po3rin.re
> +// 長い為改行
このコメントは編集前のメモですかね？

2019-03-31 01:33 UTC, budougumi0617 commented on articles/po3rin.re
> +func DrawMask(
もっと手前で言えよって感じですが、標準パッケージとか参照するときは脚注でコードのURLを書いておくとか
https://github.com/golang/go/blob/go1.12.1/src/image/draw/draw.go#L100

2019-03-31 05:06 UTC, po3rin commented on articles/po3rin.re
> +// 長い為改行
ここは読者に意図的に改行していることを補足しています。URLが長くてlistのブロックからはみ出てしまう為、改行しています。

2019-03-31 05:15 UTC, po3rin commented on articles/po3rin.re
> +また、今回の章で使用するダウンロードデータを皆さんが金銭の発生する二次利用として利用してしまうと法律的にアウトなのでご了承ください。
Goのロゴだけもう一回確認して、個別の条件をちゃんと整理します。もうしばらくお待ちください！

2019-03-31 05:16 UTC, po3rin commented on articles/po3rin.re
> +初めましてpo3rinです。業務ではGo言語をメインに使って開発しています。この章ではGoによる画像処理&画像解析の方法を紹介します。最初は入門から始まり、中盤からは様々な画像処理のTipsを紹介します。終盤では更に突っ込んでOpenCVを使った顔認識や輪郭抽出などの方法を紹介します。初めての方でもこの章を読み終える頃には、Goでエレガントに画像を扱えるようになっていることでしょう。ソースコード
4部構成なので最初、中盤、終盤という表現を消します！

2019-03-31 05:16 UTC, po3rin commented on articles/po3rin.re
> +初めましてpo3rinです。業務ではGo言語をメインに使って開発しています。この章ではGoによる画像処理&画像解析の方法を紹介します。最初は入門から始まり、中盤からは様々な画像処理のTipsを紹介します。終盤では更に突っ込んでOpenCVを使った顔認識や輪郭抽出などの方法を紹介します。初めての方でもこの章を読み終える頃には、Goでエレガントに画像を扱えるようになっていることでしょう。ソースコード
それは知りませんでした！ありがとうございます！

2019-03-31 06:39 UTC, po3rin commented on articles/po3rin.re
> +まずはGoで画像を扱う際の中心になるimageパッケージの基本を押さえましょう。このタイミングで@tottieさんのGopherくんのイラスト(@<img>{po3rin-tottie-gopher})をダウンロードしておいてください。
ありがとうございます。読みやすい押さえるで統一します！

2019-03-31 07:09 UTC, po3rin commented on articles/po3rin.re
> +まずは画像ファイルを@<code>{image.Image}の型に変換して画像のデータをみてみましょう。
インターフェースで統一します！

2019-03-31 07:13 UTC, po3rin commented on articles/po3rin.re
> +RGBAとは、ディスプレイ画面で色を表現するために用いられる、赤（Red）、緑（Green）、青（Blue）の3色に、アルファ（Alpha）と呼ばれる透過度の情報を加えたもののです。RGBチャンネルにアルファ値が乗算されている形式をPre-multiplied Alpha(乗算済みアルファ)、乗算されていない形式をStraight Alphaと呼びます。Goのimage/colorパッケージでは
確かに指摘いただいた内容の方がわかりやすいので、修正します！

2019-03-31 07:15 UTC, po3rin commented on articles/po3rin.re
> +@<code>{image.Image}の実装を@<list>{image_Image}でみてみましょう。今回使った3つのメソッドを持つインターフェースになっています。先ほど確認したように、それぞれのメソッドは画像の基本的な情報を返します。
全体的に```@<code>{image.Image}インターフェース```という表現に変えます！

2019-03-31 07:16 UTC, po3rin commented on articles/po3rin.re
> +Goではpng,jpeg,gifの画像フォーマットが標準パッケージでサポートされています。1点注意があり、画像フォーマットのパッケージの関数などを使わない場合でも@<code>{import _ image/png}のようにブランクインポートで対応するを読み込んでおかないと実行時にエラーが発生します。理由を探る為に@<code>{image/png/reader.go}をみてみましょう。
typoです。ありがとうございます！

2019-03-31 07:19 UTC, po3rin commented on articles/po3rin.re
> +@<list>{grayscale}の通り、Goで画像加工をする際には、まず目的の画像(dstと呼ぶ)を作成し、元画像(srcと呼ぶ)から1画素ずつ処理してdstにセットするという流れになります。今回においてはsrcから1画素値づつ所得し、その色をグレースケール化してdstにセットしています。濃淡加工やセピア加工などのエフェクト処理においてもこのフローは鉄板なので覚えておきましょう。
ピクセルを全て　画素に統一しました！

2019-03-31 07:28 UTC, po3rin commented on articles/po3rin.re
> +// getLerpParam 1軸に対して、Lerpで使うパラメータと近傍点をdstの座標と拡大縮小比率から所得する関数
つけるように統一します！

2019-03-31 07:29 UTC, po3rin commented on articles/po3rin.re
> +func DrawMask(
そうですね。書き加えます。

2019-03-31 07:57 UTC, po3rin commented on articles/po3rin.re
> +また、今回の章で使用するダウンロードデータを皆さんが金銭の発生する二次利用として利用してしまうと法律的にアウトなのでご了承ください。
この本においては全て一次利用&商用利用可となる物を選んでいます。読者がこの画像を使う条件はもう一度確認します！

2019-03-31 08:05 UTC, po3rin commented on articles/po3rin.re
> +今回、@tottieさんのGopher@<fn>{gopher}くんのイラストの利用許可を頂きました。@<img>{po3rin-tottie-gopher}などの素敵なイラストを描いている方です。是非Twitter等で検索してみて下さい。
つけました！

2019-03-31 08:09 UTC, po3rin commented on articles/po3rin.re
> +func Lerp(f PosDependFunc, a float64, b float64, ps Points) float64 {
いただいた内容で統一します！

2019-03-31 08:15 UTC, po3rin commented on articles/po3rin.re
> +@<list>{getimg}では@<code>{png.Decode}で標準入力を@<code>{image.Image}型にデコードしています。@<list>{getimg}を@<list>{rungo}のように実行すると画像の縦横の長さや、色についての情報が確認出来ます。
全体的に@<code>の後に補足をつけました

2019-03-31 08:38 UTC, po3rin commented on articles/po3rin.re
> +初めましてpo3rinです。業務ではGo言語をメインに使って開発しています。この章ではGoによる画像処理&画像解析の方法を紹介します。最初は入門から始まり、中盤からは様々な画像処理のTipsを紹介します。終盤では更に突っ込んでOpenCVを使った顔認識や輪郭抽出などの方法を紹介します。初めての方でもこの章を読み終える頃には、Goでエレガントに画像を扱えるようになっていることでしょう。ソースコード
何章か確定してないので一旦3章としておいておきます。

2019-03-31 10:34 UTC, po3rin commented on articles/po3rin.re
> +初めましてpo3rinです。業務ではGo言語をメインに使って開発しています。この章ではGoによる画像処理&画像解析の方法を紹介します。最初は入門から始まり、中盤からは様々な画像処理のTipsを紹介します。終盤では更に突っ込んでOpenCVを使った顔認識や輪郭抽出などの方法を紹介します。初めての方でもこの章を読み終える頃には、Goでエレガントに画像を扱えるようになっていることでしょう。ソースコード
節への参照の貼り方がネットで見つからないのですが(調べ方が悪いかも。。)、何か書き方の例などはありますか？。。

2019-03-31 11:17 UTC, budougumi0617 commented on articles/po3rin.re
> +初めましてpo3rinです。業務ではGo言語をメインに使って開発しています。この章ではGoによる画像処理&画像解析の方法を紹介します。最初は入門から始まり、中盤からは様々な画像処理のTipsを紹介します。終盤では更に突っ込んでOpenCVを使った顔認識や輪郭抽出などの方法を紹介します。初めての方でもこの章を読み終える頃には、Goでエレガントに画像を扱えるようになっていることでしょう。ソースコード
<img width="754" alt="スクリーンショット 2019-03-31 20 15 56" src="https://user-images.githubusercontent.com/1883265/55288386-e1add380-53f1-11e9-93ee-a6aca8ba9e61.png">

この辺ですかね！
https://github.com/golangtokyo/shoten5/blob/e5bd66d0cbc0bc40636d1e02c6ccee6f17bf0ea3/articles/budougumi0617.re#L288

https://github.com/golangtokyo/shoten5/blob/e5bd66d0cbc0bc40636d1e02c6ccee6f17bf0ea3/articles/budougumi0617.re#L450

2019-03-31 11:20 UTC, budougumi0617 commented on articles/po3rin.re
> +// 長い為改行
なるほど！コンテキストがないと分かりづらいので、「では@<code>{draw.DrawMask}の引数をみていきましょう。」の脚注として「紙面の都合上改行をしています」とか追加しておくとかですかね。

2019-03-31 11:27 UTC, po3rin commented on articles/po3rin.re
> +初めましてpo3rinです。業務ではGo言語をメインに使って開発しています。この章ではGoによる画像処理&画像解析の方法を紹介します。最初は入門から始まり、中盤からは様々な画像処理のTipsを紹介します。終盤では更に突っ込んでOpenCVを使った顔認識や輪郭抽出などの方法を紹介します。初めての方でもこの章を読み終える頃には、Goでエレガントに画像を扱えるようになっていることでしょう。ソースコード
おお！ありがとうございます！

2019-03-31 11:28 UTC, po3rin commented on articles/po3rin.re
> +// 長い為改行
承知しました！

2019-03-31 12:13 UTC, po3rin commented on articles/po3rin.re
> +初めましてpo3rinです。業務ではGo言語をメインに使って開発しています。この章ではGoによる画像処理&画像解析の方法を紹介します。最初は入門から始まり、中盤からは様々な画像処理のTipsを紹介します。終盤では更に突っ込んでOpenCVを使った顔認識や輪郭抽出などの方法を紹介します。初めての方でもこの章を読み終える頃には、Goでエレガントに画像を扱えるようになっていることでしょう。ソースコード
節への参照を貼ると少し説明が助長かなと感じました。。。

<img width="820" alt="スクリーンショット 2019-03-31 20 55 08" src="https://user-images.githubusercontent.com/29445112/55288815-ea090d00-53f7-11e9-93ed-8bc6b015df3a.png">

 こんな感じで、節への参照を貼らないシンプルなリード文でも良い気がしましたがいかがでしょうか。
<img width="824" alt="スクリーンショット 2019-03-31 21 12 30" src="https://user-images.githubusercontent.com/29445112/55288906-c646c680-53f9-11e9-9270-55c2afd013bb.png">

2019-03-31 13:26 UTC, po3rin commented on articles/po3rin.re
> +また、今回の章で使用するダウンロードデータを皆さんが金銭の発生する二次利用として利用してしまうと法律的にアウトなのでご了承ください。
配布に関してまだ詰めれていなかったですね。申し訳ないです。。

Goのロゴに関するライセンスはCC Attribution 3.0の為、ブランドガイドラインに従えば、商用利用、配布可能です。https://blog.golang.org/go-brand

画像ごとに利権が違うのは毎回説明することになり面倒なので、Goのロゴと同じライセンスをもつ画像に差し替えます。

一方でtottieさんの画像は独自の契約で「読者は金銭の発生する二次利用は不可」という条件で二次配布OKをもらっているので、その旨を注意書きで記載する形でいかがでしょうか。金銭が発生しなければ二次利用OKかどうかは作者に確認しています。

2019-03-31 13:28 UTC, po3rin commented on articles/po3rin.re
> +また、今回の章で使用するダウンロードデータを皆さんが金銭の発生する二次利用として利用してしまうと法律的にアウトなのでご了承ください。
こちらに調査結果と考えをまとめました
https://github.com/golangtokyo/shoten6/pull/2#discussion_r270666415

2019-04-06 07:04 UTC, po3rin commented on articles/po3rin.re
> +また、今回の章で使用するダウンロードデータを皆さんが金銭の発生する二次利用として利用してしまうと法律的にアウトなのでご了承ください。
こちらのサイトの画像に差し替えます。こちらがライセンスです。配布も可能なの凄すぎますね。。
https://unsplash.com/license

2019-04-06 11:12 UTC, budougumi0617 commented on articles/po3rin.re
> +また、今回の章で使用するダウンロードデータを皆さんが金銭の発生する二次利用として利用してしまうと法律的にアウトなのでご了承ください。
unsplash、私もスライド作る時によく使いますｗ

2019-04-06 13:03 UTC, budougumi0617 commented on articles/po3rin.re
> +では必要な素材を準備する関数を作りましょう。必要なのは@<code>{src}(Goのロゴ)と@<code>{cover}(背景画像)と@<code>{mask}(背景画像をマスキングする画像)と@<code>{dst}(合成を受ける画像)です。画像はそれぞれOGP画像の大きさに合うように前節で実装したリサイズ関数を使いましょう。前節の実装を飛ばした方は、@<code>{github.com/p
> 用意したのそちらを使いましょう。

タイポ？

2019-04-06 13:03 UTC, budougumi0617 commented on articles/po3rin.re
> +今回、画像の合成においては@<img>{po3rin-synthesis-flow}のようなフローを踏みます。背景画像にマスクをかけて@<code>{dst}に合成し、Goのロゴをその上から@<code>{dst}に合成します。矢印に紐づいている関数の意味は後ほど説明します。
「フローを踏む」ってあまり聞かない気がしますね。（ググってもあまり出てこない）
手順を踏む、段階を踏む、ですかね。

2019-04-06 13:03 UTC, budougumi0617 commented on articles/po3rin.re
> +@<code>{NewRect}関数はdstとmaskを作る為の関数です。1画素ごとに引数で受け取った色をセットしているだけです。そして、GetCoverとGetSrcはそれぞれ合成する画像を読み込んでOGP画像の大きさに合うようにリサイズしています。@<list>{getimagefunc}で作った関数を使って画像合成をしてみましょう。
> GetCoverとGetSrc

装飾忘れ。

2019-04-06 13:03 UTC, budougumi0617 commented on articles/po3rin.re
> +@<code>{draw.DrawMask}関数は、srcをmaskでマスキングしてdst内に配置します。srcの中で合成に使う位置がsp、maskの中でマスキングに使う位置がmpです。opはPorter-Duffコンポジションの演算子で、２枚の画像を合成する際にそれぞれのピクセルについてどのように処理するかを規定したものです。Goでは二つの演算子を提供しており、今回はOver演算子を使って指定
全体的に装飾忘れです。

2019-04-06 13:03 UTC, budougumi0617 commented on articles/po3rin.re
> +@<code>{draw.DrawMask}関数は、srcをmaskでマスキングしてdst内に配置します。srcの中で合成に使う位置がsp、maskの中でマスキングに使う位置がmpです。opはPorter-Duffコンポジションの演算子で、２枚の画像を合成する際にそれぞれのピクセルについてどのように処理するかを規定したものです。Goでは二つの演算子を提供しており、今回はOver演算子を使って指定
> 指定されたdstの上にastを重ねています

astはタイポですか？

2019-04-06 13:03 UTC, budougumi0617 commented on articles/po3rin.re
> +分かりにくいのは@<code>{freetype.Context.SetSrc}メソッドです。なぜここで真っ白な画像を渡しているのでしょうか。@<code>{freetype.Context.DrawString}メソッドの実装を見ると、内部で@<code>{draw.DrawMask}関数が実行されています。ここでは@<code>{src}に対しテキストの形のマスクをかけています。その為、@<
> なぜここで真っ白な画像を渡しているのでしょうか。

これの答えってなんでしょうか。「なぜここで真っ白な画像を渡しているのか」の答えは「白色の文字を合成したいから」ではないですか？
他の補足を抜いて単純に「なぜここで真っ白な画像を渡しているのか」→「`@<code>{src}`の色がそのままテキストの色になっているのです。」と並べると「なぜ」に対する答えるの文にはなっていないように読めます。

2019-04-06 13:07 UTC, budougumi0617 commented
残りを一通りみました。

2019-04-07 02:00 UTC, po3rin commented on articles/po3rin.re
> +分かりにくいのは@<code>{freetype.Context.SetSrc}メソッドです。なぜここで真っ白な画像を渡しているのでしょうか。@<code>{freetype.Context.DrawString}メソッドの実装を見ると、内部で@<code>{draw.DrawMask}関数が実行されています。ここでは@<code>{src}に対しテキストの形のマスクをかけています。その為、@<
疑問符の後にすぐに答えを書くようにしました。

2019-04-07 02:00 UTC, po3rin commented on articles/po3rin.re
> +@<code>{draw.DrawMask}関数は、srcをmaskでマスキングしてdst内に配置します。srcの中で合成に使う位置がsp、maskの中でマスキングに使う位置がmpです。opはPorter-Duffコンポジションの演算子で、２枚の画像を合成する際にそれぞれのピクセルについてどのように処理するかを規定したものです。Goでは二つの演算子を提供しており、今回はOver演算子を使って指定
typoでした。修正しました

2019-04-07 02:01 UTC, po3rin commented on articles/po3rin.re
> +今回、画像の合成においては@<img>{po3rin-synthesis-flow}のようなフローを踏みます。背景画像にマスクをかけて@<code>{dst}に合成し、Goのロゴをその上から@<code>{dst}に合成します。矢印に紐づいている関数の意味は後ほど説明します。
手順を踏むという表現に統一しました

2019-04-07 02:01 UTC, po3rin commented on articles/po3rin.re
> +では必要な素材を準備する関数を作りましょう。必要なのは@<code>{src}(Goのロゴ)と@<code>{cover}(背景画像)と@<code>{mask}(背景画像をマスキングする画像)と@<code>{dst}(合成を受ける画像)です。画像はそれぞれOGP画像の大きさに合うように前節で実装したリサイズ関数を使いましょう。前節の実装を飛ばした方は、@<code>{github.com/p
typoです。修正しました。

2019-04-07 02:03 UTC, po3rin commented on articles/po3rin.re
> +また、今回の章で使用するダウンロードデータを皆さんが金銭の発生する二次利用として利用してしまうと法律的にアウトなのでご了承ください。
tottieさんに確認し、細かい利用条件を聞いてきたので、それを掲載しました。

2019-04-07 02:03 UTC, po3rin commented
いただいた指摘箇所は一通り修正しました。

2019-04-07 23:05 UTC, skanehira commented on articles/po3rin.re
> +初めましてpo3rinです。業務ではGoをメインに使って開発しています。この章ではGoによる画像処理&画像解析の方法を紹介します。画像処理の入門はもちろん、標準パッケージのみを使った画像リサイズの実装や、画像や文字を合成する方法を紹介し、最後にはOpenCVを使った顔認識や輪郭抽出の実装を紹介します。Goでエレガントに画像を扱えるようになっていることでしょう。ソースコードは全て私のGitHubリ
>Goでエレガントに画像を扱えるようになっていることでしょう。

「本章を読み終わった頃には」という意味ですか？

2019-04-07 23:07 UTC, skanehira commented on articles/po3rin.re
> +初めましてpo3rinです。業務ではGoをメインに使って開発しています。この章ではGoによる画像処理&画像解析の方法を紹介します。画像処理の入門はもちろん、標準パッケージのみを使った画像リサイズの実装や、画像や文字を合成する方法を紹介し、最後にはOpenCVを使った顔認識や輪郭抽出の実装を紹介します。Goでエレガントに画像を扱えるようになっていることでしょう。ソースコードは全て私のGitHubリ
>ちなみにこの節のコードは実際の処理のみ

節ではなく章だと思います

2019-04-07 23:17 UTC, skanehira commented on articles/po3rin.re
> +@<list>{image_register}のように@<code>{init}関数@<fn>{init}で使える画像フォーマットをパッケージ内の@<code>{init}関数内で登録しています。その為、init関数を発火させる為にブランクインポートをする必要があります。
>@<list>{image_register}のように@<code>{init}関数@<fn>{init}で使える画像フォーマットをパッケージ内の@<code>{init}関数内で登録しています。

一つめにinit関数はどこのパッケージを指しているのでしょうか？
「init関数で使える画像をパッケージのinit関数内で登録している」だと理解できませんでした…

>その為、init関数を発火させる為にブランクインポートをする必要があります。

その為のあとに為には変な気がするので
`その為、init関数を発火させるにはブランクインポートをする必要があります。`
はどうでしょうか？

2019-04-07 23:20 UTC, skanehira commented on articles/po3rin.re
> +@<list>{grayscale}の通り、Goで画像加工をする際には、まず目的の画像(@<code>{dst}と呼ぶ)を作成し、元画像(@<code>{src}と呼ぶ)から1画素ずつ処理して@<code>{dst}にセットするという流れになります。今回においてはsrcから1画素値づつ所得し、その色をグレースケール化して@<code>{dst}にセットしています。濃淡加工やセピア加工などのエフェ
「ずつ」と「づつ」が混在しているので統一しておきましょう。

2019-04-07 23:28 UTC, skanehira commented on articles/po3rin.re
> +では必要な素材を準備する関数を作りましょう。必要なのは@<code>{src}(Goのロゴ)と@<code>{cover}(背景画像)と@<code>{mask}(背景画像をマスキングする画像)と@<code>{dst}(合成を受ける画像)です。画像はそれぞれOGP画像の大きさに合うように前節で実装したリサイズ関数を使いましょう。前節の実装を飛ばした方は、@<code>{github.com/p
>前節の実装を飛ばした方は、github.com/po3rin/resizeパッケージとして全く同じリサイズ機能を提供するパッケージを用意したのでそちらを使いましょう。

github.com/po3rin/resizeパッケージを用意したという解釈で合っていますか？
合っているならば、「前節の実装を飛ばした方は、全く同じリサイズ機能を提供するgithub.com/po3rin/resizeパッケージを用意したのでそちらを使いましょう。」のがわかりやすいかなと思います。

2019-04-07 23:39 UTC, skanehira commented on articles/po3rin.re
> +輪郭抽出の結果を使って@<code>{gocv.DrawContours}関数(@<list>{drawContours})で輪郭の中を白色で塗りつぶします。@<code>{contours}は輪郭のデータです。第3引数@<code>{contourIdx}は描画したい輪郭のインデックス(第2引数で与えた輪郭のsliceから1つの輪郭だけを描画したいときに輪郭の指定に使います。全輪郭を描画する時
PDFにすると`-1`が`ー1`になるようです。
何かしらで`-1`を囲ったほうが良いかと思います

![image](https://user-images.githubusercontent.com/7888591/55691518-c2a6d700-59d9-11e9-9e96-26096967b351.png)

2019-04-07 23:41 UTC, skanehira requested changes
気になるところコメントしました

2019-04-08 01:09 UTC, po3rin commented on articles/po3rin.re
> +初めましてpo3rinです。業務ではGoをメインに使って開発しています。この章ではGoによる画像処理&画像解析の方法を紹介します。画像処理の入門はもちろん、標準パッケージのみを使った画像リサイズの実装や、画像や文字を合成する方法を紹介し、最後にはOpenCVを使った顔認識や輪郭抽出の実装を紹介します。Goでエレガントに画像を扱えるようになっていることでしょう。ソースコードは全て私のGitHubリ
完全に文が消えてました。。ありがとうございます！！

2019-04-08 01:12 UTC, po3rin commented on articles/po3rin.re
> +@<list>{image_register}のように@<code>{init}関数@<fn>{init}で使える画像フォーマットをパッケージ内の@<code>{init}関数内で登録しています。その為、init関数を発火させる為にブランクインポートをする必要があります。
例であげているinit関数については文の手前で参照をあげています。
https://github.com/golangtokyo/shoten6/pull/2/files/0ba5d4ab92308e4cff3f52d5333c65df1a2e7eaa#diff-dc8ea8a74915ea08595e8ba3d59a9baeR86

為為の件は修正します

2019-04-08 01:13 UTC, po3rin commented on articles/po3rin.re
> +@<list>{grayscale}の通り、Goで画像加工をする際には、まず目的の画像(@<code>{dst}と呼ぶ)を作成し、元画像(@<code>{src}と呼ぶ)から1画素ずつ処理して@<code>{dst}にセットするという流れになります。今回においてはsrcから1画素値づつ所得し、その色をグレースケール化して@<code>{dst}にセットしています。濃淡加工やセピア加工などのエフェ
全く気付きませんでした。。

2019-04-08 01:19 UTC, po3rin commented on articles/po3rin.re
> +では必要な素材を準備する関数を作りましょう。必要なのは@<code>{src}(Goのロゴ)と@<code>{cover}(背景画像)と@<code>{mask}(背景画像をマスキングする画像)と@<code>{dst}(合成を受ける画像)です。画像はそれぞれOGP画像の大きさに合うように前節で実装したリサイズ関数を使いましょう。前節の実装を飛ばした方は、@<code>{github.com/p
いただいた文章で修正しました！！

2019-04-08 01:21 UTC, po3rin commented on articles/po3rin.re
> +輪郭抽出の結果を使って@<code>{gocv.DrawContours}関数(@<list>{drawContours})で輪郭の中を白色で塗りつぶします。@<code>{contours}は輪郭のデータです。第3引数@<code>{contourIdx}は描画したい輪郭のインデックス(第2引数で与えた輪郭のsliceから1つの輪郭だけを描画したいときに輪郭の指定に使います。全輪郭を描画する時
@<code>{}で囲いました。

<img width="596" alt="スクリーンショット 2019-04-08 10 17 45" src="https://user-images.githubusercontent.com/29445112/55693067-f7ba2600-59e7-11e9-8948-4082d8e128cd.png">

2019-04-08 01:25 UTC, po3rin commented
一箇所だけ解決してませんが、いただいた指摘を修正しました！

2019-04-08 20:33 UTC, budougumi0617 approved these changes
自分のが出来ていない体たらくなので流し見になってしまいましたが、私はLGTM！

2019-04-10 03:56 UTC, po3rin commented
timakinさんの寄稿を受けてタイトルを変更しました。timakiさんがデザインパターンに重きを置いているのに対して、こちらは画像処理にフォーカスするという意味で「Goによる画像処理のエッセンス」にしました(高校時代にお世話になった「物理のエッセンス」というタイトルから)

2019-04-10 10:44 UTC, merged