vimで快適にGoを書くため
golangtokyo/shoten6 pull request #3
Opened 2019-03-23 05:07 UTC by skanehira

書きました

2019-03-27 16:49 UTC, budougumi0617 reviewed
ひとまず内容だけ確認しました。

2019-03-27 16:49 UTC, budougumi0617 commented on articles/gorilla.re
> +普段はvimを使ってGoを書くことが趣味で、@<br>{}
文の途中で改行はしないほうがいいですね。

2019-03-27 16:49 UTC, budougumi0617 commented on articles/gorilla.re
> +基本モードを切り替えながらコーディングします。@<br>{}
句読点がなく「基本モード」という概念があるようにと読めるので"基本的に"や"基本、モードを"のほうがよいです。

2019-03-27 16:49 UTC, budougumi0617 commented on articles/gorilla.re
> +それぞれのモードでできることは大まかに以下になります。
”以下”というような言葉は原則使わないでください。論文や本を書くときは参照を貼って「表X.Xのようになります」というような書き方になります。
（RE:VIEWは箇条書きに対し参照を貼れなかった気がするので"次のように”のようにかくか、表に書き換える必要があります）

2019-03-27 16:49 UTC, budougumi0617 commented on articles/gorilla.re
> +vimを触ったことがない方は、こちらの基本操作を覚えておきましょう。@<br>{}
”次のように”や”以下のように"と同様に”こちら”という表現もだめです。

2019-03-27 16:49 UTC, budougumi0617 commented on articles/gorilla.re
> +`yy/Y`で行をコピーします。
`yy/Y`って4文字入力するとコピーされるんですか？どこの行がコピーされるんですか？1行目ですか？
vimを知らない人にこの表記で伝わりますか？書き方の凡例をまず書いておいほうがいい気がします。

2019-03-27 16:49 UTC, budougumi0617 commented on articles/gorilla.re
> +==== undo・redo
ほかは日本語になっているのにここだけ英語なのは理由がありますか？

2019-03-27 16:49 UTC, budougumi0617 commented on articles/gorilla.re
> +insert modeで`esc`で抜けることができます。
insert modeは`esc`で抜けることができます。

2019-03-27 16:49 UTC, budougumi0617 commented on articles/gorilla.re
> +このモードでは範囲選択ができ、選択した範囲に対して`y/Y/d/D/p/P`と行ったオペレーションが可能です。
typo 行った

2019-03-27 16:49 UTC, budougumi0617 commented on articles/gorilla.re
> +このモードでは範囲選択ができ、選択した範囲に対して`y/Y/d/D/p/P`と行ったオペレーションが可能です。
`y/Y/d/D/p/P`

スラッシュの意味を定義していないので一文字ずつスラッシュを挟む11文字入力する操作に見えます。

2019-03-27 16:49 UTC, budougumi0617 commented on articles/gorilla.re
> +オプションについてはオススメvimrc設定で紹介します。
後述の項目のことを指しているならば参照を貼ってください

2019-03-27 16:49 UTC, budougumi0617 commented on articles/gorilla.re
> +`/`も置換対象の場合は`\/`でエスケープしなければのはご注意ください。
typo しなければのは

2019-03-27 16:49 UTC, budougumi0617 commented on articles/gorilla.re
> +Goを書く時に、欠かせないプラグインとしてvim-goというのがあります。@<br>{}
> vim-go

何かを紹介するときはリファレンス貼っておきましょう.

https://github.com/fatih/vim-go

2019-03-27 16:49 UTC, budougumi0617 commented on articles/gorilla.re
> +dein.vimの導入については、$HOME/.vimrcに以下の部分を先頭に追記してください。@<br>{}
"以下"って何を指していますか？参照を貼りましょう

2019-03-27 16:49 UTC, budougumi0617 commented on articles/gorilla.re
> +===== $HOME/.vim/dein.tomlにファイルを作成して以下を先頭に追加してください。
> $HOME/.vim/dein.tomlにファイルを作成して

$HOME/.vim/dein.tomlという名前のファイルを作成して

2019-03-27 16:49 UTC, budougumi0617 commented on articles/gorilla.re
> +===== $HOME/.vim/dein.tomlにファイルを作成して以下を先頭に追加してください。
NG 以下

2019-03-27 16:49 UTC, budougumi0617 commented on articles/gorilla.re
> +上記を追加後、vimを立ち上げるとdein.vimとvim-goのインストールが開始され、しばらくすると終わります。@<br>{}
NG 上記

2019-03-27 16:49 UTC, budougumi0617 commented on articles/gorilla.re
> +以下のコマンドをvimのcommand line modeで@<code>{:GoInstallBinaries}実行してください。
NG 以下

2019-03-27 16:49 UTC, budougumi0617 commented on articles/gorilla.re
> +以下のコマンドをvimのcommand line modeで@<code>{:GoInstallBinaries}実行してください。
このあとは特に指摘しませんが、"以下"や"こちら”というような表記は参照を貼って直してください。

2019-03-27 16:49 UTC, budougumi0617 commented on articles/gorilla.re
> +@<code>{Ctrl+]}もしくは@<code>{gd}でカーソル上にある定義へジャンプすることができます。@<br>{}
カーソル上にある定義へ -> カーソル上にある識別子の定義元へ

カーソル上に定義があるならば、そこが定義なのでジャンプしないですよね。

2019-03-27 16:49 UTC, budougumi0617 commented on articles/gorilla.re
> +プラグイン内部でGoDefコマンドを実行しているだけです。@<br>{}
次の行のGoDegはコード表記になっていますが、この行は生でGoDegって書いてあります。コード表記にするならば全ての箇所でコード表記にしましょう。

2019-03-27 16:49 UTC, budougumi0617 commented on articles/gorilla.re
> +=== 関数移動
厳密に言うと関数だけでなく、メソッドでもできますよね。（この指摘はちょっといちゃもん感ある）

2019-03-27 16:49 UTC, budougumi0617 commented on articles/gorilla.re
> +@<code>{:FillStruct}で構造体のをゼロ値で初期化( T{} ) --> ( T{A: 1, B: 2, C: 3})することができます。@<br>{}
GoFillStruct

2019-03-27 16:49 UTC, budougumi0617 commented on articles/gorilla.re
> +@<code>{:FillStruct}で構造体のをゼロ値で初期化( T{} ) --> ( T{A: 1, B: 2, C: 3})することができます。@<br>{}
( T{} ) --> ( T{A: 1, B: 2, C: 3}
暗黙的にこの例は`type T struct {A,B, C int}`という構造体定義があることを前提としています。明示的に書いてください。

2019-03-27 16:49 UTC, budougumi0617 commented on articles/gorilla.re
> +どんなキーがあったか忘れたときなどに使うと便利です。
どんなフィールド

https://golang.org/ref/spec#Struct_types
構造体の要素はGoでは通常フィールドと呼びます。キーとは呼ばないです。
`StructType    = "struct" "{" { FieldDecl ";" } "}" .`

2019-03-27 16:49 UTC, budougumi0617 commented on articles/gorilla.re
> +@<code>{:GoKeyify}でキーなしの構造体リテラル( T{1, 2, 3} )をキー付き構造体リテラル( T{A: 1, B: 2, C: 3} )にすることができます@<br>{}
NG キー

2019-03-27 16:49 UTC, budougumi0617 commented on articles/gorilla.re
> +執筆時点でvim-goはLSPに対応したので、Go公式のgoplsを使用して補完と定義ジャンプが可能になっています。@<br>{}
略語をいきなり使うのはやめましょう。Language Server Protocol(LSP)です。

2019-03-27 16:49 UTC, budougumi0617 commented on articles/gorilla.re
> +執筆時点でvim-goはLSPに対応したので、Go公式のgoplsを使用して補完と定義ジャンプが可能になっています。@<br>{}
もしくは脚注を使います。

2019-03-27 16:49 UTC, budougumi0617 commented on articles/gorilla.re
> +執筆時点でvim-goはLSPに対応したので、Go公式のgoplsを使用して補完と定義ジャンプが可能になっています。@<br>{}
goplsのリファレンス

2019-03-27 16:49 UTC, budougumi0617 commented on articles/gorilla.re
> +検索したい単語にカーソルを当てた状態で開く`*`でファイル検索できます。@<br>{}
開く？

2019-03-27 16:49 UTC, budougumi0617 commented on articles/gorilla.re
> +また、@<code>{:vsp gorilla.go}というふうに引数を渡すことで分割したウィンドウで指定したファイルを開くことができます。
ふうに は口語な気がするので　ように　ですかね

2019-03-27 16:49 UTC, budougumi0617 commented on articles/gorilla.re
> +set relativenumber
知りませんでした、いつもヤンクするとき数えてました。すごい。（小並感）

2019-03-27 16:49 UTC, budougumi0617 commented on articles/gorilla.re
> +ここでは、筆者が使用しているdein.vimというプラグインマネージャをもとに解説していきます。@<br>{}
deinのリファレンス

2019-03-28 02:06 UTC, tenntenn commented on articles/gorilla.re
> += vimでGoを快適に書く
正式名称はVimですかね？

2019-03-28 03:03 UTC, tenntenn requested changes
以下のようなことを意識して見直すと良いでしょう。

* 装飾については頑張らない
  * 組版ソフトが勝手にやります
  * 書籍全体を通して統一感を図ることが難しくなります
  * 表記の仕方や表現方法も統一しておくと読みやすいでしょう
* 説明を丁寧にする
  * 定義していない略語、用語などをきちんと説明しましょう
  * 前提条件はきちんと丁寧に行いましょう
  * 読者は書いてあることをすべて覚えていません。都度丁寧に表現しましょう。
* 口語を避ける
  * https://www.ipentec.com/document/write-thesis-tips が参考になります
  * すっきりした言い回しを心がけましょう
  * macOSの読み上げ機能を使うと分かりづらい部分が明確になります
* 正しい情報を載せる
  * 製品名やソフトウェアの名前は開発者に敬意を払い正式名称を書きましょう
  * 言語に関する部分やVimの仕様に関する部分は誤解がうまれない表現で正しく表記しましょう
  * 言語仕様などの1次情報を参照して誤った表現をしていないか確認しましょう
* 書籍であることを意識しましょう
  * Webで公開されるものではないので、「上下」の概念などは避けましょう
  * ソースコードとそれに対する説明がページをまたぐ可能性があるため、listを使って番号で参照するようにしましょう
  * 時間に関する表現は注意しましょう

2019-03-28 03:03 UTC, tenntenn commented on articles/gorilla.re
> +始めまして、ゴリラです。
はじめまして

2019-03-28 03:03 UTC, tenntenn commented on articles/gorilla.re
> +普段はvimを使ってGoを書くことが趣味で、@<br>{}
改行はすべて組版ソフトに任せましょう。改行を無理にするとスタイルを変えたりする場合におかしくなります。

2019-03-28 03:03 UTC, tenntenn commented on articles/gorilla.re
> +主にTUIツールを作ることが多いです。@<br>{}
略称を使う場合は最初は何の略か書いたほうがよいです

2019-03-28 03:03 UTC, tenntenn commented on articles/gorilla.re
> +本章は以下の環境をもとに解説していきます。
本に上下の概念はないので、「次の環境を」

2019-03-28 03:03 UTC, tenntenn commented on articles/gorilla.re
> +@<b>{OS}@<br>{}
太字にする意味はなさそうです。

2019-03-28 03:03 UTC, tenntenn commented on articles/gorilla.re
> +それぞれのモードでできることは大まかに以下になります。
表で良さそうです

2019-03-28 03:03 UTC, tenntenn commented on articles/gorilla.re
> +vimを触ったことがない方は、こちらの基本操作を覚えておきましょう。@<br>{}
「次のように」はまだ許容範囲だとは思います。基本的には表番号等で参照するのがよいですが。

2019-03-28 03:03 UTC, tenntenn commented on articles/gorilla.re
> +下記に記載がなければ、基本normal modeでの操作になります。
`下記` -> `後述`

`基本`という言葉を多様しすぎている気がします。
違う言い回しや、そもそも付けなくても意味が通る場合は付けないでよいと思います。

2019-03-28 03:03 UTC, tenntenn commented on articles/gorilla.re
> +==== undo・redo
カタカナでよいかと

2019-03-28 03:03 UTC, tenntenn commented on articles/gorilla.re
> +オプションについてはオススメvimrc設定で紹介します。
インライン検索ですかね

2019-03-28 03:03 UTC, tenntenn commented on articles/gorilla.re
> +Goを書く時に、欠かせないプラグインとしてvim-goというのがあります。@<br>{}
footnoteで注釈を書いておくとよいと思います。また、その中でhrefを使うとPDFになったときにリンクがはられます。

2019-03-28 03:03 UTC, tenntenn commented on articles/gorilla.re
> +dein.vimの導入については、$HOME/.vimrcに以下の部分を先頭に追記してください。@<br>{}
`$HOME`はmacOSやLinuxなどの場合に限られるので、Windowsユーザにも配慮しましょう。

2019-03-28 03:03 UTC, tenntenn commented on articles/gorilla.re
> +dein.vimの導入については、$HOME/.vimrcに以下の部分を先頭に追記してください。@<br>{}
パスなどには@codeを使っていったほうが良さそうですね。

2019-03-28 03:03 UTC, tenntenn commented on articles/gorilla.re
> +なお、導入はgitが必要なので事前にインストールしておいてください。
正式名称はGitで、gitはコマンド名かと思います。

2019-03-28 03:03 UTC, tenntenn commented on articles/gorilla.re
> +//emlist[go][toml]{
emlistではなくlistを使ってください

2019-03-28 03:03 UTC, tenntenn commented on articles/gorilla.re
> +===== dein.vimを導入するため、以下を$HOME/.vimrcの先頭に追加してください。
これって見出しですか？
RE:Viewは見た目のために`=`は使わないようにお願いします。

2019-03-28 03:03 UTC, tenntenn commented on articles/gorilla.re
> +//emlist[dein][vimscript]{
list

2019-03-28 03:03 UTC, tenntenn commented on articles/gorilla.re
> +vim-goではファイル保存時に自動的にフォーマットしてくれるので、忘れても大丈夫です。
「フォーマット」と「整形」のどちらかに統一してください。
あと、忘れてはダメだと思います。
「意識しなくてすみます」などの表現にしたほうがよいです。
「大丈夫」も口語っぽくなるので使わないほうがよいでしょう。

2019-03-28 03:03 UTC, tenntenn commented on articles/gorilla.re
> +@<code>{:GoImports}で構文解析して、必要なパッケージをimportしてくれたり、不要なパッケージを削除してくれます。@<br>{}
構文解析だけではできません。
型チェックも必要となるので「解析して」くらいにしておいたほうが無難かと思います。

「〇〇してくれる」は冗長な表現なので「〇〇する」の方がよいです。

2019-03-28 03:03 UTC, tenntenn commented on articles/gorilla.re
> +=== 関数移動
正しく書くことは非常に大事です。「関数（メソッド）間の移動」など誤解のない見出しにすると良いでしょう。

2019-03-28 03:03 UTC, tenntenn commented on articles/gorilla.re
> +@<code>{yif}で関数の中身、@<code>{yaf}で関数全体をコピーできます。@<br>{}
同様にyifで...

2019-03-28 03:03 UTC, tenntenn commented on articles/gorilla.re
> +引数がなければ、デフォルトはjsonタグが追加されますが、@<br>{}
`json`タグで伝わらないと思います。
また、コード上の表現は`@code{}`でくくり、一般名称はくくらないでおくなどのポリシーを持ったほうがよいです。

2019-03-28 03:03 UTC, tenntenn commented on articles/gorilla.re
> +@<code>{:GoAddTags yaml toml}の様に引数を渡すことで複数のタグを追加することができます。@<br>{}
「様に」と「ように」を統一。
漢字が多いと誌面が黒くなって読みづらいので、「ように」の方がよいと思います。

2019-03-28 03:03 UTC, tenntenn commented on articles/gorilla.re
> +引数を渡すことで、指定したタグを削除することもできます。
タグが2つのことを指しています。
`json:"hoge" yaml:"fuga"`もタグと呼び、その一部の`json:"hoge"`もタグと読んでいます。
前者はGoの言語仕様上もタグとなっているので、後者の表現を変更すべきだと思います。

`reflect`パッケージのGoDocを見ると「キー
」が適切かと思います。
https://golang.org/pkg/reflect/#StructTag.Lookup

2019-03-28 03:03 UTC, tenntenn commented on articles/gorilla.re
> +=== godocを開く
GoDoc

2019-03-28 03:03 UTC, tenntenn commented on articles/gorilla.re
> +筆者は後者のが好みです。
好みな理由も添えた方がよいです。理由を添えない場合は、読者にとってメリットが無いので、あえて言う必要はないでしょう。

2019-03-28 03:03 UTC, tenntenn commented on articles/gorilla.re
> +@<code>{:GoImplements}でカーソル上にあるインターフェイスを実装した構造体を探すことができます。@<br>{}
インタフェースを実装するのは構造体だけではありません。
https://qiita.com/tenntenn/items/eac962a49c56b2b15ee8

2019-03-28 03:03 UTC, tenntenn commented on articles/gorilla.re
> +@<code>{:FillStruct}で構造体のをゼロ値で初期化( T{} ) --> ( T{A: 1, B: 2, C: 3})することができます。@<br>{}
謎の記号の`--->`はどういう意味でしょうか？
日本語で表現するか、きっちり定義した上で記号を使うべきです。

2019-03-28 03:03 UTC, tenntenn commented on articles/gorilla.re
> +@<code>{:GoKeyify}でキーなしの構造体リテラル( T{1, 2, 3} )をキー付き構造体リテラル( T{A: 1, B: 2, C: 3} )にすることができます@<br>{}
フィールド名

2019-03-28 03:03 UTC, tenntenn commented on articles/gorilla.re
> +リファクタリングするときに便利です。
主語

2019-03-28 03:03 UTC, tenntenn commented on articles/gorilla.re
> +@<code>{:GoImpl}でカーソルを当てた構造体に、指定したインターフェイスの関数を自動生成できます。@<br>{}
構造体だけですか？

2019-03-28 03:03 UTC, tenntenn commented on articles/gorilla.re
> +インターフェイスを指定するとき、$GOPATH/src以降のパス.インターフェイス名で指定する必要があります。@<br>{}
インポートパスと表記した方がよいです。
`vendor`もありますし、Go Modules導入後は`$GOPATH`の下とは限りません。

2019-03-28 03:03 UTC, tenntenn commented on articles/gorilla.re
> +ただし、Goの標準パッケージの場合はインターフェイス名のみで問題ないです。@<br>{}
「問題ありません。」

2019-03-28 03:03 UTC, tenntenn commented on articles/gorilla.re
> +大量にメソッドが定義されている場合、コマンド一つでスタブをつくれるのは魅力的ですね。
Goでは大量のメソッドがあるインタフェースを良しとはしない文化です。
この例ではなく、`テスト用にモックを手早く作る場合に便利でしょう`などとするほうが良いです。

NG ですね

2019-03-28 03:03 UTC, tenntenn commented on articles/gorilla.re
> +@<code>{:GoPlay}でソースをGoplaygroundにアップロードできます。@<br>{}
The Go Playground

2019-03-28 03:03 UTC, tenntenn commented on articles/gorilla.re
> +ローカルで書いたサンプルをシェアする時に便利です。
どういったものをローカルと表現していますか？
「Vimで書いたコードをThe Go Playground上でシェアする場合に便利です。」

2019-03-28 03:03 UTC, tenntenn commented on articles/gorilla.re
> +執筆時点でvim-goはLSPに対応したので、Go公式のgoplsを使用して補完と定義ジャンプが可能になっています。@<br>{}
「執筆時点」は具体的にいつでしょうか。
また、対応しているvim-goのバージョンはいくつでしょう？
書籍はいつ読まれるのか予想できないため、時間に関する表現は相対的ではなく絶対的な表現にすべきです。

2019-03-28 03:03 UTC, tenntenn commented on articles/gorilla.re
> +一旦PCを再起動するときなど、何かしらの理由で作業を中断せざるを得ない場合に使うと便利です。@<br>{}
パソコンを再起動する場合など

2019-03-28 03:03 UTC, tenntenn commented on articles/gorilla.re
> +もしくはvimを開いた状態なら@<code>{:source xxx.vim}で復元できます。
またはVimを開いた状態であれば@<code>{:source xxx.vim}で復元することもできます。

2019-03-28 03:03 UTC, tenntenn commented on articles/gorilla.re
> +`IsGorilla` という関数名があって、それを `IsHuman` に修正したい場合、@<br>{}
もう少し前提を丁寧にしましょう。listを使って具体的なコードを示した上で説明するとより明確になります。

2019-03-28 03:03 UTC, tenntenn commented on articles/gorilla.re
> +カーソルをGにおいた状態でcwでGorillaを削除してinsert modeになるのでそこでHumanを入力することでサクッと修正できます。
`cw`とかの表現はキーを押すことを表すことをどこかで定義した方が良さそうです。
できれば、通常の文章とは書式を変えてほしいです。

2019-03-28 03:03 UTC, tenntenn commented on articles/gorilla.re
> +カーソルをGにおいた状態でcwでGorillaを削除してinsert modeになるのでそこでHumanを入力することでサクッと修正できます。
>そこでHumanを入力することでサクッと修正できます。
そこで`@<code>{Human}`と入力することで簡単に修正することができます。

口語っぽいので、文語で書きましょう。

2019-03-28 03:03 UTC, tenntenn commented on articles/gorilla.re
> +また、@<code>{:vsp gorilla.go}というふうに引数を渡すことで分割したウィンドウで指定したファイルを開くことができます。
同様に`という`も口語です。

「開くことができます。」より「開けます。」の方が短くてわかりやすいでしょう。

2019-03-28 03:03 UTC, tenntenn commented on articles/gorilla.re
> +これは入れておけという設定をすこし紹介していきます。
丁寧な表現に

2019-03-28 03:03 UTC, tenntenn commented on articles/gorilla.re
> +設定したらもっと便利になります。
そんな保証はないと思うので、適切な表現に変えましょう。

2019-03-28 03:03 UTC, tenntenn commented on articles/gorilla.re
> +//emlist[vimrc][vimscript]{
list

2019-03-28 03:03 UTC, tenntenn commented on articles/gorilla.re
> +個人的にオススメのプラグインを紹介します。@<br>{}
個人的であることを主張する必要はないでしょう。

2019-03-28 04:21 UTC, budougumi0617 commented on articles/gorilla.re
> +vimを触ったことがない方は、こちらの基本操作を覚えておきましょう。@<br>{}
なるほど、たしかに `the following changes` みたいな表現結構みますね。
指摘ミスでした、ありがとうございます 🙇

2019-03-28 23:21 UTC, skanehira commented on articles/gorilla.re
> +dein.vimの導入については、$HOME/.vimrcに以下の部分を先頭に追記してください。@<br>{}
Windows:%HOME%
Mac/Linux:$HOME
といった注釈が必要という理解であってますか？

2019-03-28 23:21 UTC, skanehira commented on articles/gorilla.re
> +dein.vimの導入については、$HOME/.vimrcに以下の部分を先頭に追記してください。@<br>{}
Windows:%HOME%
Mac/Linux:$HOME
といった注釈が必要という理解であってますか？

2019-03-28 23:24 UTC, skanehira commented on articles/gorilla.re
> += vimでGoを快適に書く
vimとVim、どちらでも良いそうです
現時点、公式も統一されていないため、ここでは全て小文字で統一してます。

2019-04-05 06:22 UTC, po3rin reviewed
ちらっと読んで気になったところにコメントしました。

2019-04-05 06:22 UTC, po3rin commented on articles/gorilla.re
> +insert modeで`esc`で抜けることができます。
```esc```で抜けるのは指から遠く、スピードが落ちるので「ctrl + c」で 抜けれることも一緒に追記した方が良いのではないでしょうか。

2019-04-05 06:22 UTC, po3rin commented on articles/gorilla.re
> +執筆時点でvim-goはLSPに対応したので、Go公式のgoplsを使用して補完と定義ジャンプが可能になっています。@<br>{}
僕のようなVim素人的にはLSPとは何かについても言及した方が親切かもしれません。

2019-04-05 16:55 UTC, po3rin commented on articles/gorilla.re
> +set relativenumber
この辺すごく便利ですぐ導入しました！

2019-04-05 16:55 UTC, po3rin commented on articles/gorilla.re
> +set relativenumber
この辺すごく便利ですぐ導入しました！

2019-04-07 00:52 UTC, skanehira commented on articles/gorilla.re
> += vimでGoを快適に書く
Vimに統一しました

2019-04-07 00:52 UTC, skanehira commented on articles/gorilla.re
> +始めまして、ゴリラです。
修正しました

2019-04-07 00:54 UTC, skanehira commented on articles/gorilla.re
> +普段はvimを使ってGoを書くことが趣味で、@<br>{}
改行をしないようにしました

2019-04-07 00:54 UTC, skanehira commented on articles/gorilla.re
> +主にTUIツールを作ることが多いです。@<br>{}
補足入れました

2019-04-07 00:54 UTC, skanehira commented on articles/gorilla.re
> +本章は以下の環境をもとに解説していきます。
修正しました

2019-04-07 00:56 UTC, skanehira commented on articles/gorilla.re
> +@<b>{OS}@<br>{}
`@<br>` を外しました

2019-04-07 00:57 UTC, skanehira commented on articles/gorilla.re
> +基本モードを切り替えながらコーディングします。@<br>{}
修正しました

2019-04-07 01:13 UTC, skanehira commented on articles/gorilla.re
> +それぞれのモードでできることは大まかに以下になります。
表にしました

2019-04-07 01:14 UTC, skanehira commented on articles/gorilla.re
> +==== undo・redo
カタカナにしました

2019-04-07 05:56 UTC, skanehira commented on articles/gorilla.re
> +なお、導入はgitが必要なので事前にインストールしておいてください。
Gitに修正しました

2019-04-07 05:57 UTC, skanehira commented on articles/gorilla.re
> +===== $HOME/.vim/dein.tomlにファイルを作成して以下を先頭に追加してください。
修正しました

2019-04-07 05:57 UTC, skanehira commented on articles/gorilla.re
> +===== $HOME/.vim/dein.tomlにファイルを作成して以下を先頭に追加してください。
`次の` に修正しました

2019-04-07 06:12 UTC, skanehira commented on articles/gorilla.re
> +//emlist[go][toml]{
`list`を使うようにしました

2019-04-07 06:12 UTC, skanehira commented on articles/gorilla.re
> +//emlist[dein][vimscript]{
修正しました

2019-04-07 06:26 UTC, skanehira commented on articles/gorilla.re
> +===== dein.vimを導入するため、以下を$HOME/.vimrcの先頭に追加してください。
見出しではないので削除しました

2019-04-07 06:27 UTC, skanehira commented on articles/gorilla.re
> +上記を追加後、vimを立ち上げるとdein.vimとvim-goのインストールが開始され、しばらくすると終わります。@<br>{}
なくても問題ないので削除しました

2019-04-07 07:00 UTC, skanehira commented on articles/gorilla.re
> +以下のコマンドをvimのcommand line modeで@<code>{:GoInstallBinaries}実行してください。
文言を変更し、以下を使わないようにしました

2019-04-07 07:25 UTC, skanehira commented on articles/gorilla.re
> +@<code>{Ctrl+]}もしくは@<code>{gd}でカーソル上にある定義へジャンプすることができます。@<br>{}
ご指摘通り、日本語が変なので修正しました

2019-04-07 07:26 UTC, skanehira commented on articles/gorilla.re
> +プラグイン内部でGoDefコマンドを実行しているだけです。@<br>{}
修正しました

2019-04-07 07:27 UTC, skanehira commented on articles/gorilla.re
> +vim-goではファイル保存時に自動的にフォーマットしてくれるので、忘れても大丈夫です。
文言修正しました

2019-04-07 07:30 UTC, skanehira commented on articles/gorilla.re
> +@<code>{:GoImports}で構文解析して、必要なパッケージをimportしてくれたり、不要なパッケージを削除してくれます。@<br>{}
文言修正しました

2019-04-07 07:33 UTC, skanehira commented on articles/gorilla.re
> +=== 関数移動
`関数（メソッド）間の移動`に修正しました

2019-04-07 07:33 UTC, skanehira commented on articles/gorilla.re
> +@<code>{yif}で関数の中身、@<code>{yaf}で関数全体をコピーできます。@<br>{}
修正しました

2019-04-07 07:35 UTC, skanehira commented on articles/gorilla.re
> +@<code>{:GoAddTags yaml toml}の様に引数を渡すことで複数のタグを追加することができます。@<br>{}
`ように`に統一しました

2019-04-07 07:38 UTC, skanehira commented on articles/gorilla.re
> +下記に記載がなければ、基本normal modeでの操作になります。
文言修正しました

2019-04-07 07:38 UTC, skanehira commented on articles/gorilla.re
> +`yy/Y`で行をコピーします。
表にして、,でキーを区切るようにしました

2019-04-07 07:39 UTC, skanehira commented on articles/gorilla.re
> +insert modeで`esc`で抜けることができます。
表にして、`esc, ctrl+c`に修正しました

2019-04-07 07:40 UTC, skanehira commented on articles/gorilla.re
> +このモードでは範囲選択ができ、選択した範囲に対して`y/Y/d/D/p/P`と行ったオペレーションが可能です。
表にしました

2019-04-07 07:40 UTC, skanehira commented on articles/gorilla.re
> +このモードでは範囲選択ができ、選択した範囲に対して`y/Y/d/D/p/P`と行ったオペレーションが可能です。
表にして、分けました

2019-04-07 07:40 UTC, skanehira commented on articles/gorilla.re
> +オプションについてはオススメvimrc設定で紹介します。
表にして、この文言を削除しました

2019-04-07 07:41 UTC, skanehira commented on articles/gorilla.re
> +`/`も置換対象の場合は`\/`でエスケープしなければのはご注意ください。
表にしましたに。
エスケープの話は除去しました

2019-04-07 07:45 UTC, skanehira commented on articles/gorilla.re
> +個人的にオススメのプラグインを紹介します。@<br>{}
`個人的`を除去しました

2019-04-07 07:46 UTC, skanehira commented on articles/gorilla.re
> +//emlist[vimrc][vimscript]{
修正しました

2019-04-07 07:47 UTC, skanehira commented on articles/gorilla.re
> +これは入れておけという設定をすこし紹介していきます。
文言修正しました

2019-04-07 07:47 UTC, skanehira commented on articles/gorilla.re
> +設定したらもっと便利になります。
文言修正しました

2019-04-07 07:49 UTC, skanehira commented on articles/gorilla.re
> +また、@<code>{:vsp gorilla.go}というふうに引数を渡すことで分割したウィンドウで指定したファイルを開くことができます。
文言修正しました

2019-04-07 07:49 UTC, skanehira commented on articles/gorilla.re
> +検索したい単語にカーソルを当てた状態で開く`*`でファイル検索できます。@<br>{}
不要な文字が混じったので、除去しました

2019-04-07 07:52 UTC, skanehira commented on articles/gorilla.re
> +もしくはvimを開いた状態なら@<code>{:source xxx.vim}で復元できます。
修正しました

2019-04-07 07:53 UTC, skanehira commented on articles/gorilla.re
> +一旦PCを再起動するときなど、何かしらの理由で作業を中断せざるを得ない場合に使うと便利です。@<br>{}
修正しました

2019-04-07 07:54 UTC, skanehira commented on articles/gorilla.re
> +ローカルで書いたサンプルをシェアする時に便利です。
`Vimで書いたコードをThe Go Playground上でシェアする場合に便利です。` に修正しました

2019-04-07 07:54 UTC, skanehira commented on articles/gorilla.re
> +@<code>{:GoPlay}でソースをGoplaygroundにアップロードできます。@<br>{}
修正しました

2019-04-07 07:55 UTC, skanehira commented on articles/gorilla.re
> +大量にメソッドが定義されている場合、コマンド一つでスタブをつくれるのは魅力的ですね。
`テスト用にモックを手早く作る場合に便利でしょう`に修正しました

2019-04-07 07:55 UTC, skanehira commented on articles/gorilla.re
> +ただし、Goの標準パッケージの場合はインターフェイス名のみで問題ないです。@<br>{}
修正しました

2019-04-07 07:56 UTC, skanehira commented on articles/gorilla.re
> +インターフェイスを指定するとき、$GOPATH/src以降のパス.インターフェイス名で指定する必要があります。@<br>{}
修正しました

2019-04-07 07:57 UTC, skanehira commented on articles/gorilla.re
> +リファクタリングするときに便利です。
主語追記しました

2019-04-07 07:58 UTC, skanehira commented on articles/gorilla.re
> +@<code>{:GoKeyify}でキーなしの構造体リテラル( T{1, 2, 3} )をキー付き構造体リテラル( T{A: 1, B: 2, C: 3} )にすることができます@<br>{}
修正しました

2019-04-07 07:58 UTC, skanehira commented on articles/gorilla.re
> +どんなキーがあったか忘れたときなどに使うと便利です。
修正しました

2019-04-07 07:58 UTC, skanehira commented on articles/gorilla.re
> +@<code>{:FillStruct}で構造体のをゼロ値で初期化( T{} ) --> ( T{A: 1, B: 2, C: 3})することができます。@<br>{}
修正しました

2019-04-07 08:00 UTC, skanehira commented on articles/gorilla.re
> +筆者は後者のが好みです。
理由を添えました

2019-04-07 08:01 UTC, skanehira commented on articles/gorilla.re
> +=== godocを開く
修正しました

2019-04-07 08:43 UTC, skanehira commented on articles/gorilla.re
> +@<code>{:GoImplements}でカーソル上にあるインターフェイスを実装した構造体を探すことができます。@<br>{}
そうでした
文言修正しました

2019-04-07 15:29 UTC, skanehira commented on articles/gorilla.re
> +vimを触ったことがない方は、こちらの基本操作を覚えておきましょう。@<br>{}
表番号を参照するようにしました

2019-04-07 15:30 UTC, skanehira commented on articles/gorilla.re
> +Goを書く時に、欠かせないプラグインとしてvim-goというのがあります。@<br>{}
footnoteに注釈を書くようにしました

2019-04-07 15:30 UTC, skanehira commented on articles/gorilla.re
> +ここでは、筆者が使用しているdein.vimというプラグインマネージャをもとに解説していきます。@<br>{}
footnoteに注釈を書くようにしました

2019-04-07 15:36 UTC, skanehira commented on articles/gorilla.re
> +引数がなければ、デフォルトはjsonタグが追加されますが、@<br>{}
コードを追記してわかりやすくしました

2019-04-07 15:50 UTC, skanehira commented on articles/gorilla.re
> +執筆時点でvim-goはLSPに対応したので、Go公式のgoplsを使用して補完と定義ジャンプが可能になっています。@<br>{}
- LSP
- 執筆時点
について脚注を追加しました

2019-04-07 15:50 UTC, skanehira commented on articles/gorilla.re
> +執筆時点でvim-goはLSPに対応したので、Go公式のgoplsを使用して補完と定義ジャンプが可能になっています。@<br>{}
脚注を追加しました

2019-04-07 16:08 UTC, skanehira commented on articles/gorilla.re
> +カーソルをGにおいた状態でcwでGorillaを削除してinsert modeになるのでそこでHumanを入力することでサクッと修正できます。
>できれば、通常の文章とは書式を変えてほしいです。
他の箇所は@<code>{}を使っているので、それに統一します

2019-04-07 16:09 UTC, skanehira commented on articles/gorilla.re
> +@<code>{:GoImpl}でカーソルを当てた構造体に、指定したインターフェイスの関数を自動生成できます。@<br>{}
構造体だけではないのですが、明記せずコードを使って説明するようにしました。

2019-04-07 16:25 UTC, skanehira commented on articles/gorilla.re
> +引数を渡すことで、指定したタグを削除することもできます。
文言修正しました

2019-04-07 16:26 UTC, skanehira commented on articles/gorilla.re
> +@<code>{:FillStruct}で構造体のをゼロ値で初期化( T{} ) --> ( T{A: 1, B: 2, C: 3})することができます。@<br>{}
コードを追加してわかりやすくしました

2019-04-07 16:37 UTC, skanehira commented on articles/gorilla.re
> +`IsGorilla` という関数名があって、それを `IsHuman` に修正したい場合、@<br>{}
コードを追加してわかりやすくしました

2019-04-07 17:21 UTC, skanehira commented on articles/gorilla.re
> +set relativenumber
他にもいくつか追加しました

2019-04-07 17:23 UTC, skanehira commented on articles/gorilla.re
> +執筆時点でvim-goはLSPに対応したので、Go公式のgoplsを使用して補完と定義ジャンプが可能になっています。@<br>{}
>僕のようなVim素人的にはLSPとは何かについても言及した方が親切かもしれません。

LSPに関しては、正式名称を脚注したので、そちらを調べてもらうようにしようと思います。

2019-04-08 14:32 UTC, budougumi0617 reviewed
遅くてごめんなさい。またみました。

2019-04-08 14:32 UTC, budougumi0617 commented on articles/gorilla.re
> +はじめまして、ゴリラです。
ごめんなさい、最初に確認しておくべきでした。Twitterアカウントなど脚注にかかなくていいですか？
ゴリラ.vim主催してます、みたいな宣伝とか入っていてもいいですよ。。ｗ

2019-04-08 14:32 UTC, budougumi0617 commented on articles/gorilla.re
> +Vim	8.1.950
Goのバージョンはいらないですか？

2019-04-08 14:32 UTC, budougumi0617 commented on articles/gorilla.re
> +各モードでできる操作は大まか@<table>{mode}になります。
大まか「に」？

2019-04-08 14:32 UTC, budougumi0617 commented on articles/gorilla.re
> +導入はGitが必要なので事前にインストールしておいてください。
導入「に」は？

2019-04-08 14:32 UTC, budougumi0617 commented on articles/gorilla.re
> +Vimのcommandline modeで@<code>{:GoInstallBinaries}実行してください。
「を」実行してください。

2019-04-08 14:32 UTC, budougumi0617 commented on articles/gorilla.re
> +構造体のフィールドにカーソルを置き、@<code>{:GoAddTags}で次のようにタグを追加することができます。
> 次のよう

参照ですかね。

2019-04-08 14:32 UTC, budougumi0617 commented on articles/gorilla.re
> +}
タグ消えていない？？

2019-04-08 14:32 UTC, budougumi0617 commented on articles/gorilla.re
> +@<code>{:GoFillStruct}で次のように構造体のをゼロ値で初期化することができます。
`次のように`

参照？

2019-04-08 14:32 UTC, budougumi0617 commented on articles/gorilla.re
> +@<code>{:GoPlay}でコードをThe Go Playgroundにアップロードできます。
リンクあったほうがいいですね。

2019-04-08 14:32 UTC, budougumi0617 commented on articles/gorilla.re
> +			\ 'left': [ ['mode', 'paste'], ['readonly', 'filepath', 'modified'] ]
<img width="953" alt="スクリーンショット 2019-04-08 23 31 08" src="https://user-images.githubusercontent.com/1883265/55732147-6c2bae00-5a56-11e9-9f87-193d039543ff.png">

ここはみ出てるのではみ出てるので調整したほうがいいです。

2019-04-08 15:21 UTC, tenntenn commented on articles/gorilla.re
> +普段はVimを使ってGoを書くことが趣味で@<fn>{tui}TUIツールを作るのが好きです。
footnoteは後ろじゃないですかね？
TUI@<fn>{tui}

2019-04-08 15:21 UTC, tenntenn commented on articles/gorilla.re
> +各モードでできる操作は大まか@<table>{mode}になります。
`それぞれのモードでできる代表的な操作をまとめると@<table>{mode}のようになります。`

2019-04-08 15:21 UTC, tenntenn commented on articles/gorilla.re
> +基本操作をわかっている方は飛ばして頂いて問題ありません。
この文はなくてもよさそう。下の文と同じような意味なので。

2019-04-08 15:21 UTC, tenntenn commented on articles/gorilla.re
> +Goを書くときに欠かせないプラグインとしてvim-go@<fn>{vim-go}があります。
`Goを書く` -> `Goのコードを書く`

2019-04-08 15:21 UTC, tenntenn commented on articles/gorilla.re
> +導入はGitが必要なので事前にインストールしておいてください。
`導入`より`インストール`とかの方がわかりやすそう。
導入のままでも良いですが、主語はあったほうがよい。例：`vim-goの導入には`

2019-04-08 15:21 UTC, tenntenn commented on articles/gorilla.re
> +また、本章の中に{HOME}が複数回出ますが、@<table>{home}の通りに読み替えてください。
パスの区切り文字にもついでに言及しておくとよいです。

2019-04-08 15:21 UTC, tenntenn commented on articles/gorilla.re
> +また、@<code>{:GoAddTags yaml toml}のように引数を渡すことで@<list>{goaddtags_yaml_toml}のように複数のタグを追加することもできます。
再掲
`json`や`yaml`はタグではない。
フィールドに書けるタグは1つだけ。

2019-04-08 15:21 UTC, tenntenn commented on articles/gorilla.re
> +次のように構造体のフォールドにカーソルを当てた状態で@<code>{:GoRemoveTag}で構造体のタグを削除することができます。
`次のように`が何を指しているのか分からない。
コードリストを指すなら`@<code>`で参照すべきだし、カーソルの位置であればどのフィールドにカーソルを当ててるか詳しく書くべき。

2019-04-08 15:21 UTC, tenntenn commented on articles/gorilla.re
> +また、@<code>{:GoRemoveTag toml}のように引数を渡すことで、次のように指定したキーのタグを削除することもできます。
`タグから指定したキーを削除することもできます`
言語仕様にはタグが1つしか無いことが分かります。
https://golang.org/ref/spec#Struct_types
あくまで、タグをキーで区切って使うのは`reflect`パッケージの機能です。
1つのタグの中にキーで区切って複数の値が並べてあるということなので、タグは1つです。
そのため、タグを消すとすべてのキーが消えます。

`vim-go`上ではタグを消すという機能（`GoRemoveTag`）かもしれませんが、Goの言語仕様の方が正しいです。

2019-04-08 15:21 UTC, tenntenn commented on articles/gorilla.re
> +@<code>{:GoRename}でカーソルを当てた変数や関数が使われている箇所をすべてリネームできます。
リネームされるのは識別子であって箇所ではない。
```
@<code>{:GoRename}でカーソルを当てた変数や関数などの識別子をリネームできます。
なお、指定した識別子を使用しているすべての箇所でリネームが行われます。
```

2019-04-08 15:21 UTC, tenntenn commented on articles/gorilla.re
> +@<code>{:GoImpl}で次のようにカーソルを当てたTに指定したインターフェイスのメソッドスタブを生成できます。
`T`が型なのかわかりにくいので、`型@<code>{T}`とする。

2019-04-08 15:21 UTC, tenntenn commented on articles/gorilla.re
> +インターフェイスを指定するとき、インポートパス.インターフェイス名で指定する必要があります。
`インターフェイスは、"インポートパス.インターフェイス名"の形で指定する必要があります。`

2019-04-08 15:21 UTC, tenntenn commented on articles/gorilla.re
> +ただし、Goの標準パッケージの場合はインターフェイス名のみで問題ありません。
`ただし、Goの標準パッケージで提供されるインタフェースはインポートパスを省いても構いません。`

2019-04-08 15:21 UTC, tenntenn commented on articles/gorilla.re
> +テスト用にモックを手早く作る場合に便利でしょう。
`メソッドスタブを作る機能は、テスト用にモックを手早く作る場合に便利でしょう。`
などして、主語をちゃんと付ける。

2019-04-08 15:21 UTC, tenntenn commented on articles/gorilla.re
> +=== 構造体の中身をコピー or 削除
`or`じゃなくて、`構造体の中身をコピー／削除`にする。
急に英語を使わない。

2019-04-08 15:52 UTC, skanehira commented on articles/gorilla.re
> +普段はVimを使ってGoを書くことが趣味で@<fn>{tui}TUIツールを作るのが好きです。
修正しました

2019-04-08 15:53 UTC, skanehira commented on articles/gorilla.re
> +基本操作をわかっている方は飛ばして頂いて問題ありません。
そうですね
削除しました

2019-04-08 15:53 UTC, skanehira commented on articles/gorilla.re
> +Goを書くときに欠かせないプラグインとしてvim-go@<fn>{vim-go}があります。
修正しました

2019-04-08 15:57 UTC, skanehira commented on articles/gorilla.re
> +@<code>{:GoImpl}で次のようにカーソルを当てたTに指定したインターフェイスのメソッドスタブを生成できます。
修正しました

2019-04-08 15:57 UTC, skanehira commented on articles/gorilla.re
> +インターフェイスを指定するとき、インポートパス.インターフェイス名で指定する必要があります。
修正しました

2019-04-08 15:58 UTC, skanehira commented on articles/gorilla.re
> +ただし、Goの標準パッケージの場合はインターフェイス名のみで問題ありません。
修正しました

2019-04-08 15:58 UTC, skanehira commented on articles/gorilla.re
> +テスト用にモックを手早く作る場合に便利でしょう。
修正しました

2019-04-08 15:59 UTC, skanehira commented on articles/gorilla.re
> +=== 構造体の中身をコピー or 削除
修正しました

2019-04-08 16:00 UTC, skanehira commented on articles/gorilla.re
> +はじめまして、ゴリラです。
がっつり宣伝しました

2019-04-08 16:03 UTC, skanehira commented on articles/gorilla.re
> +Vim	8.1.950
追記しました

2019-04-08 16:03 UTC, skanehira commented on articles/gorilla.re
> +各モードでできる操作は大まか@<table>{mode}になります。
tenntennさん指摘通り修正しました

2019-04-08 16:03 UTC, skanehira commented on articles/gorilla.re
> +導入はGitが必要なので事前にインストールしておいてください。
文言を修正しました

2019-04-08 16:04 UTC, skanehira commented on articles/gorilla.re
> +Vimのcommandline modeで@<code>{:GoInstallBinaries}実行してください。
修正しました

2019-04-08 16:06 UTC, skanehira commented on articles/gorilla.re
> +構造体のフィールドにカーソルを置き、@<code>{:GoAddTags}で次のようにタグを追加することができます。
修正しました

2019-04-08 16:07 UTC, skanehira commented on articles/gorilla.re
> +}
修正しました

2019-04-08 16:07 UTC, skanehira commented on articles/gorilla.re
> +@<code>{:GoFillStruct}で次のように構造体のをゼロ値で初期化することができます。
修正しました

2019-04-08 16:08 UTC, skanehira commented on articles/gorilla.re
> +@<code>{:GoPlay}でコードをThe Go Playgroundにアップロードできます。
修正しました

2019-04-08 16:19 UTC, skanehira commented on articles/gorilla.re
> +			\ 'left': [ ['mode', 'paste'], ['readonly', 'filepath', 'modified'] ]
修正しました

2019-04-08 23:57 UTC, skanehira commented on articles/gorilla.re
> +また、本章の中に{HOME}が複数回出ますが、@<table>{home}の通りに読み替えてください。
追記しました

2019-04-08 23:58 UTC, skanehira commented on articles/gorilla.re
> +@<code>{:GoRename}でカーソルを当てた変数や関数が使われている箇所をすべてリネームできます。
修正しました

2019-04-09 00:10 UTC, budougumi0617 commented on articles/gorilla.re
> +はじめまして、都内でゴリラ.vim@<fn>{gorilla.vim}を主催しているVim好きなゴリです。
あれ、ゴリラじゃなくて、Vim好きな「ゴリ」でしたっけ？

2019-04-10 10:42 UTC, merged