GoとKafkaを用いた分散メッセージシステム入門
golangtokyo/shoten6 pull request #5
Opened 2019-04-07 18:23 UTC by syossan27

2019-04-07 21:28 UTC, budougumi0617 reviewed
一通りみました。構成自体には特にふれてません。

2019-04-07 21:28 UTC, budougumi0617 commented on articles/syossan27.re
> +Kafkaとは、LinkedInで開発された分散メッセージングミドルウェアです。
Kafkaのリンクが欲しいですね。章のメインなので本文中にリンクですかね。

2019-04-07 21:28 UTC, budougumi0617 commented on articles/syossan27.re
> +Kafkaとは、LinkedInで開発された分散メッセージングミドルウェアです。
LinkedInのリンクは脚注かな

2019-04-07 21:28 UTC, budougumi0617 commented on articles/syossan27.re
> +背景として、LinkedIn上での大量のアクティビティデータを機械学習やフィード画面に表示するためのデータパイプラインとして、
めのデータパイプラインとして、次の目的のために開発されました。

とか。文の間に箇条書きを割り込ませるのはあまり良くない気がします（個人的な感想）

2019-04-07 21:28 UTC, budougumi0617 commented on articles/syossan27.re
> +開発以前に、ActiveMQを使った本番環境での運用を試してみたようなのですが、メッセージキューがメモリ容量を超えると急激なパフォーマンス低下を起こしたり、負荷分散のアプローチが多数の問題により頓挫したりとかなりの苦労があったようです。
ActiveMQのリンク

2019-04-07 21:28 UTC, budougumi0617 commented on articles/syossan27.re
> +開発以前に、ActiveMQを使った本番環境での運用を試してみたようなのですが、メッセージキューがメモリ容量を超えると急激なパフォーマンス低下を起こしたり、負荷分散のアプローチが多数の問題により頓挫したりとかなりの苦労があったようです。
> かなりの苦労があったようです。

ソースの記事とか本のリンク貼れますか？

2019-04-07 21:28 UTC, budougumi0617 commented on articles/syossan27.re
> +={syossan27_title} GoとKafkaを用いた分散メッセージシステム入門
catalog.ymlに `syossan27.re`を足さないと印刷されないです。

2019-04-07 21:28 UTC, budougumi0617 commented on articles/syossan27.re
> +Brokerは１つのサーバにつき１つ存在する要素で、メッセージの受信・配信を担います。これらを複数でクラスタリングすることでメッセージングシステムの可用性を上げることが出来ます。実際に本番運用する際には必ずクラスタリングを行うようにしましょう。
「これら」ってなんですか？「Brokerが配置されたサーバ群」とかですか？指示語はなるべく使わない方がいいです。

2019-04-07 21:28 UTC, budougumi0617 commented on articles/syossan27.re
> +//}
図があるのいいですね。

2019-04-07 21:28 UTC, budougumi0617 commented on articles/syossan27.re
> +ここまでのイメージをまとめると以下のようになります。
図を文中から言及するときは「以下」じゃなくて「図X.X」みたいに参照してください。

2019-04-07 21:28 UTC, budougumi0617 commented on articles/syossan27.re
> +ActiveMQやRabbitMQのようにオーソドックスなメッセージキューイングのブローカーとして使うことが出来ます。
初出なのでRabbitMQのリンク

2019-04-07 21:28 UTC, budougumi0617 commented on articles/syossan27.re
> +他のミドルウェアと比べ、Kafkaは高スループットかつ耐障害性に勝るため、秒間のメッセージ量が多い大企業では好んで使われます。
> 耐障害性に勝る

https://dictionary.goo.ne.jp/jn/207927/meaning/m0u/

「…に」の先って比較対象だと思うので、「耐障害性において他に勝る」とかですかね。

2019-04-07 21:28 UTC, budougumi0617 commented on articles/syossan27.re
> +ただし、耐障害性を高めるための各ノードへ向けたメッセージ複製という機構やブローカーを持つため、どうしてもそれを持たないミドルウェアにはスループットが敵わない面を持ちます。
ここの主語ってなんですかね？「メッセージ複製という機構やブローカーを持つため」はKafkaが持っていると思ってよいですよね？
よくわかってないのですが、ブローカーの中にブローカーができるんですか？以下の2つのせつめいより。

- kafkaはブローカーとして使うことが出来ます。
- kafkaはブローカーを持つ

2019-04-07 21:28 UTC, budougumi0617 commented on articles/syossan27.re
> +今まで述べた通り、Kafkaは高スループットを旨としておりLinkedInでは2012年の段階でピーク時に秒間17万メッセージをも捌いている実績があります。
> 2012年の段階でピーク時に秒間17万メッセージをも捌いている実績が

データを示すときはソースを書きましょう。

2019-04-07 21:28 UTC, budougumi0617 commented on articles/syossan27.re
> +また、メッセージをHadoopなどデータウェアハウスへロードするためのconnectorが用意されているのも、好んで使われる一因だと思います。
ブローカーはカタカナだけど、connectorは英語なのは意図がありますか？

2019-04-07 21:28 UTC, budougumi0617 commented on articles/syossan27.re
> +注意点として、リプレイに必要なデータを保持するtopicの永続化に伴う適切なLog Compaction設定や、イベントをconsumeするtopic・リプライの中間データ用topicの適切な分割・設定などがあります。
この辺の英語とカタカナが混じっているのも気になりますね。kafkaの用語は英単語で、分散メッセージングの一般的な用語はカタカナなのかなと思いましたがそういうわけではない感じですかね。

2019-04-07 21:28 UTC, budougumi0617 commented on articles/syossan27.re
> + * segmentio/kafka-go
リンクを脚注に書き、 `import`するときの全文を書きましょう。これだけだとgithub.comにあるのかgitbucketにあるのか独自配信なのかわからないです。

2019-04-07 21:28 UTC, budougumi0617 commented on articles/syossan27.re
> +Shopify/saramaはこの３つの中では一番Star数が多く、またポピュラーに使われているライブラリです。筆者もShopify/saramaを用いてシステム開発を行いましたが、特に問題もなく動いてくれました。またShopify, IBM, Herokuなど大手が使っていることからも信頼性が伺えます。
> またShopify, IBM, Herokuなど大手が使っている

ここもあるならソースがほしいですね。

2019-04-07 21:28 UTC, budougumi0617 commented on articles/syossan27.re
> +今回はShopify/saramaを使って構築していきます。saramaの注意点として、以前まではbsm/sarama-clusterというライブラリも並行して使用しないとKafkaのConsumer Groupという概念を扱うことが出来なかったのですが、最近になってこのライブラリの機能がsaramaに合併されました。ですので、古い技術記事にはsarama-clusterを使ってくださいと記載さ
Shopify/saramaって言うときとsaramaって書くときがあってぶれてますね。

2019-04-07 21:28 UTC, budougumi0617 commented on articles/syossan27.re
> +それでは、まずはKafka Brokerを立ち上げていきましょう。Kafka公式サイトのQuick Startを見てBrokerを立ち上げるのも一つですが、wurstmeister/kafka-dockerという便利なプロダクトがあるのでこれを使っていきましょう。
> Kafka公式サイトのQuick Start

リンクほしいですね

2019-04-07 21:28 UTC, budougumi0617 commented on articles/syossan27.re
> +それでは、まずはKafka Brokerを立ち上げていきましょう。Kafka公式サイトのQuick Startを見てBrokerを立ち上げるのも一つですが、wurstmeister/kafka-dockerという便利なプロダクトがあるのでこれを使っていきましょう。
> wurstmeister/kafka-docker

リンク

2019-04-07 21:28 UTC, budougumi0617 commented on articles/syossan27.re
> +=== 作成するシステムについて
もろもろのバージョン書いておいてください。

2019-04-07 21:28 UTC, budougumi0617 commented on articles/syossan27.re
> +さて、ここでdocker-compose upで立ち上げたいところですが、その前に１点だけdocker-compose.ymlに修正を加えます。
どこに修正いれてるんでしょうか？明示的に書くとか、diff形式で書いたほうがいい気がしますね。

2019-04-07 21:28 UTC, budougumi0617 commented on articles/syossan27.re
> +% cd ~/kafka-docker
大したことではないですが、カレントディレクトリ直下にgit cloneしたことになってるんですかね。

2019-04-07 21:28 UTC, budougumi0617 commented on articles/syossan27.re
> +kafka-docker_zookeeper_1 0.0.0.0:2181->2181/tcp, 22/tcp, 2888/tcp, 3888/tcp
`docker_kafka_x`がブローカーですかね？
特に説明ないですが、`zookeeper`ってなんですか？Kafka知らなくても分散メッセージング知っている人なら暗黙知なんでしょうか？

2019-04-07 21:28 UTC, budougumi0617 commented on articles/syossan27.re
> +	"github.com/Shopify/sarama"
このサンプルコード`go fmt`かかってますか？

2019-04-07 21:28 UTC, budougumi0617 commented on articles/syossan27.re
> +こちらはコマンド引数として渡したBrokerのアドレスに対して、「Hello World」というメッセージをtest topicに送信する簡単なものになっています。実装としてはProducerのconfigを諸々設定し、Producerを作成・メッセージの送信という流れになっており、そこまで難しくないでしょう。
> こちらはコマンド引数として渡

どちらかわからないのでコードを指しているならば、参照してください。

2019-04-07 21:28 UTC, budougumi0617 commented on articles/syossan27.re
> +	"github.com/Shopify/sarama"
go fmt

2019-04-07 21:28 UTC, budougumi0617 commented on articles/syossan27.re
> +//listnum[producer][API実装の追加][go]{
go fmt

2019-04-07 21:28 UTC, budougumi0617 commented on articles/syossan27.re
> +これでconsumerで確認するとhelloが表示されることでしょう。さて、ここまででAPIサーバ兼Producerの役割を持つアプリケーションは完成しました。本章の最後に今回紹介した以外のProducerでの設定項目について触れていきたいと思います。
節の最後ですね。章の最後はこの`.re`ファイルの最後なので　

2019-04-07 21:28 UTC, budougumi0617 commented on articles/syossan27.re
> +これでconsumerで確認するとhelloが表示されることでしょう。さて、ここまででAPIサーバ兼Producerの役割を持つアプリケーションは完成しました。本章の最後に今回紹介した以外のProducerでの設定項目について触れていきたいと思います。
> Producerでの設定項目

構造体の説明するのならば、GoDocのリンクとかほしいですね。書いていないこともGoDoc見ればわかるので。

2019-04-07 21:28 UTC, budougumi0617 commented on articles/syossan27.re
> +基本的にはコメントで書いてあるように動くのですが、今回はSetup処理やCleanup処理は特に何もしない形で実装しております。本来であるなら、メッセージをconsumeした後によしなにデータベースへデータを挿入したりなどの処理が組み込まれますので、そういった時にHandlerでsql.DBを持ち、そこを通してデータベースのセットアップやクローズ処理をする際に使うのがベターでしょう。
> sql.DBを持ち

装飾忘れ

2019-04-07 21:28 UTC, budougumi0617 commented on articles/syossan27.re
> +ここまで読んで頂きありがとうございます。分かりにくいところもあったかもしれませんが、Kafkaの様々な概念は実際に動かしてみないと分かりづらいことが多いです。是非とも個人開発や現場で使ってみてKafkaを極めていってください。また、Kafkaの情報源として最近発売された「Apache Kafka 分散メッセージングシステムの構築と活用」という本は今回扱ったような基本的な説明から、一歩進んだ実用的
> 「Apache Kafka 分散メッセージングシステムの構築と活用」という本は

リンクありまっすか。

2019-04-07 21:28 UTC, budougumi0617 commented on articles/syossan27.re
> +ここまで読んで頂きありがとうございます。分かりにくいところもあったかもしれませんが、Kafkaの様々な概念は実際に動かしてみないと分かりづらいことが多いです。是非とも個人開発や現場で使ってみてKafkaを極めていってください。また、Kafkaの情報源として最近発売された「Apache Kafka 分散メッセージングシステムの構築と活用」という本は今回扱ったような基本的な説明から、一歩進んだ実用的
> Confluent社のBlogはKafkaの話題を

こちらもリンク入れましょう。

2019-04-07 21:28 UTC, budougumi0617 commented on articles/syossan27.re
> +//list[consumer-setting][Consumer設定一覧][]{
こちらもGoDocのリンクなどほしいですね。

2019-04-07 22:59 UTC, skanehira requested changes
気になるところについてコメントしました

2019-04-07 22:59 UTC, skanehira commented on articles/syossan27.re
> +Shopify/saramaはこの３つの中では一番Star数が多く、またポピュラーに使われているライブラリです。筆者もShopify/saramaを用いてシステム開発を行いましたが、特に問題もなく動いてくれました。またShopify, IBM, Herokuなど大手が使っていることからも信頼性が伺えます。
「くれた」は使わない方が良いそうなので、普通に「動きました」で良いかなと思います

2019-04-07 22:59 UTC, skanehira commented on articles/syossan27.re
> +今回はShopify/saramaを使って構築していきます。saramaの注意点として、以前まではbsm/sarama-clusterというライブラリも並行して使用しないとKafkaのConsumer Groupという概念を扱うことが出来なかったのですが、最近になってこのライブラリの機能がsaramaに合併されました。ですので、古い技術記事にはsarama-clusterを使ってくださいと記載さ
>最近になってこのライブラリの機能がsaramaに合併されました。

最近ではなく、時間は明示したほうが良いと思います

>記載されている場合があるかもしれませんのでご注意ください。

「かもしれません」と言い切ったあとに接続詞は変な気がします。
「かもしれないのでご注意ください」で良いかなと思います。

2019-04-07 22:59 UTC, skanehira commented on articles/syossan27.re
> +事前準備として適宜以下を行っておいてください。
[こちら](https://github.com/golangtokyo/shoten6/pull/5/files#r272851051)同様

2019-04-07 22:59 UTC, skanehira commented on articles/syossan27.re
> +これらが完了しましたら準備完了です。次にkafka-dockerの環境構築をしていきます。
>これらが完了しましたら準備完了です。次にkafka-dockerの環境構築をしていきます。

「次にkafka-dockerの環境構築をしていきます。」だけで良い気がします

2019-04-07 22:59 UTC, skanehira commented on articles/syossan27.re
> +これでtest topicを介したメッセージングの準備は出来ました。Producerを実行しているプロセスで何か文字を打ってみましょう。するとConsumerを実行しているプロセスにProducerで打った文字が表示されればKafka Brokerが正常に動いている証です。
>するとConsumerを実行しているプロセスにProducerで打った文字が表示されればKafka Brokerが正常に動いている証です。

「すると」はなくても良いと思います

2019-04-07 22:59 UTC, skanehira commented on articles/syossan27.re
> +ここからはGoの出番です。Kafkaのコマンドラインで実行していたProducerに当たる部分を実装していきます。まずはProducerのサンプルを見ていきましょう。
[こちら](https://github.com/golangtokyo/shoten6/pull/5/files#r272851051)同様

2019-04-07 22:59 UTC, skanehira commented on articles/syossan27.re
> +様々な設定がありますが、プロジェクトの規模が物凄く大きいなど特別な状況以外は特に設定することは無いものが殆どかと思われます。メッセージの量にも依るのですがKafkaのBrokerにログファイルが溜まり過ぎて、ディスク容量を食い潰して突然の死を迎えるという状況を目にしたことがあるので、筆者としてはメッセージの圧縮はやっておいた方がいいのかなと思います。
>筆者としてはメッセージの圧縮はやっておいた方がいいのかなと思います。

「やっておいたほうが良い」は話し言葉なので、
「メッセージを圧縮しておいたほうが良いと思います」
で良いかなと思います。

2019-04-08 01:35 UTC, po3rin commented on articles/syossan27.re
> +Goのシンプルな思想に惚れ込み、Goあんこ@<fn>{gounco}という勉強会の主催をやっています。
Goあんこお世話になってます

2019-04-08 02:00 UTC, po3rin reviewed
さらっと読んでコメントしました。よろしくお願いします！

2019-04-08 02:00 UTC, po3rin commented on articles/syossan27.re
> +Goのシンプルな思想に惚れ込み、Goあんこ@<fn>{gounco}という勉強会の主催をやっています。
Goあんこでお世話になってます

2019-04-08 02:00 UTC, po3rin commented on articles/syossan27.re
> +本章では、分散メッセージングミドルウェアであるKafkaをGoを通して学んでいきます。
RabbitMQからの移行を検討しているので楽しみです

2019-04-08 02:00 UTC, po3rin commented on articles/syossan27.re
> +現在も活発に更新されている代表的なライブラリは以下の３つです。
ライブラリが検討されてるの最高ですね

2019-04-08 02:00 UTC, po3rin commented on articles/syossan27.re
> +) error {
確実にnilしか返ってこないのになぜ返り値にerrorが？と一瞬思ったのですが```Shopify/sarama```のコード見ると```ConsumerGroupHandler```インターフェースを満たす為の実装ですね。初心者の方の為にこのことをどこかで説明した方が良さそうです。

2019-04-08 02:56 UTC, syossan27 commented on articles/syossan27.re
> +注意点として、リプレイに必要なデータを保持するtopicの永続化に伴う適切なLog Compaction設定や、イベントをconsumeするtopic・リプライの中間データ用topicの適切な分割・設定などがあります。
> kafkaの用語は英単語で、分散メッセージングの一般的な用語はカタカナなのかなと思いましたが
こちらその認識で合っております🙇

2019-04-08 03:23 UTC, syossan27 commented on articles/syossan27.re
> +kafka-docker_zookeeper_1 0.0.0.0:2181->2181/tcp, 22/tcp, 2888/tcp, 3888/tcp
docker_kafka_xがブローカになります。
zookeeperの説明入れ忘れておりました・・・Kafkaの基礎知識の項にzookeeperの説明を入れておきます🙇

2019-04-08 04:53 UTC, budougumi0617 commented on articles/syossan27.re
> +背景として、LinkedIn@<fn>{linkedin}上での大量のアクティビティデータを機械学習やフィード画面に表示するためのデータパイプラインとして以下を目的として開発されました。
脚注をつけるのはその用語が初出のところですね。LinkedInは15行目で出てきています。

2019-04-08 14:17 UTC, syossan27 commented on articles/syossan27.re
> +={syossan27_title} GoとKafkaを用いた分散メッセージシステム入門
追加しました！

2019-04-08 14:22 UTC, syossan27 commented on articles/syossan27.re
> +Kafkaとは、LinkedInで開発された分散メッセージングミドルウェアです。
リンク追加しました

2019-04-08 14:23 UTC, syossan27 commented on articles/syossan27.re
> +Kafkaとは、LinkedInで開発された分散メッセージングミドルウェアです。
脚注追加しました

2019-04-08 14:24 UTC, syossan27 commented on articles/syossan27.re
> +背景として、LinkedIn上での大量のアクティビティデータを機械学習やフィード画面に表示するためのデータパイプラインとして、
割り込み修正しました

2019-04-08 14:24 UTC, syossan27 commented on articles/syossan27.re
> +開発以前に、ActiveMQを使った本番環境での運用を試してみたようなのですが、メッセージキューがメモリ容量を超えると急激なパフォーマンス低下を起こしたり、負荷分散のアプローチが多数の問題により頓挫したりとかなりの苦労があったようです。
リンク追加しました

2019-04-08 14:24 UTC, syossan27 commented on articles/syossan27.re
> +開発以前に、ActiveMQを使った本番環境での運用を試してみたようなのですが、メッセージキューがメモリ容量を超えると急激なパフォーマンス低下を起こしたり、負荷分散のアプローチが多数の問題により頓挫したりとかなりの苦労があったようです。
ソース追加しました

2019-04-08 14:25 UTC, syossan27 commented on articles/syossan27.re
> +Brokerは１つのサーバにつき１つ存在する要素で、メッセージの受信・配信を担います。これらを複数でクラスタリングすることでメッセージングシステムの可用性を上げることが出来ます。実際に本番運用する際には必ずクラスタリングを行うようにしましょう。
文章修正しました

2019-04-08 14:29 UTC, syossan27 commented on articles/syossan27.re
> +ここまでのイメージをまとめると以下のようになります。
参照に修正しました

2019-04-08 14:30 UTC, syossan27 commented on articles/syossan27.re
> +ActiveMQやRabbitMQのようにオーソドックスなメッセージキューイングのブローカーとして使うことが出来ます。
追加しました

2019-04-08 14:30 UTC, syossan27 commented on articles/syossan27.re
> +他のミドルウェアと比べ、Kafkaは高スループットかつ耐障害性に勝るため、秒間のメッセージ量が多い大企業では好んで使われます。
文章修正しました

2019-04-08 14:31 UTC, syossan27 commented on articles/syossan27.re
> +ただし、耐障害性を高めるための各ノードへ向けたメッセージ複製という機構やブローカーを持つため、どうしてもそれを持たないミドルウェアにはスループットが敵わない面を持ちます。
ちょっと説明がおかしかったので修正しました

2019-04-08 14:31 UTC, syossan27 commented on articles/syossan27.re
> +今まで述べた通り、Kafkaは高スループットを旨としておりLinkedInでは2012年の段階でピーク時に秒間17万メッセージをも捌いている実績があります。
ソース追加しました

2019-04-08 14:33 UTC, syossan27 commented on articles/syossan27.re
> +また、メッセージをHadoopなどデータウェアハウスへロードするためのconnectorが用意されているのも、好んで使われる一因だと思います。
無意識にconnectorと書いておりました。カタカナに寄せておきました。

2019-04-08 14:34 UTC, syossan27 commented on articles/syossan27.re
> + * segmentio/kafka-go
脚注と全文追加しておきました

2019-04-08 14:35 UTC, syossan27 commented on articles/syossan27.re
> +Shopify/saramaはこの３つの中では一番Star数が多く、またポピュラーに使われているライブラリです。筆者もShopify/saramaを用いてシステム開発を行いましたが、特に問題もなく動いてくれました。またShopify, IBM, Herokuなど大手が使っていることからも信頼性が伺えます。
ソースの追加と文章修正しました

2019-04-08 14:35 UTC, syossan27 commented on articles/syossan27.re
> +今回はShopify/saramaを使って構築していきます。saramaの注意点として、以前まではbsm/sarama-clusterというライブラリも並行して使用しないとKafkaのConsumer Groupという概念を扱うことが出来なかったのですが、最近になってこのライブラリの機能がsaramaに合併されました。ですので、古い技術記事にはsarama-clusterを使ってくださいと記載さ
saramaに寄せて、時間の明記と文章修正しました

2019-04-08 14:36 UTC, syossan27 commented on articles/syossan27.re
> +それでは、まずはKafka Brokerを立ち上げていきましょう。Kafka公式サイトのQuick Startを見てBrokerを立ち上げるのも一つですが、wurstmeister/kafka-dockerという便利なプロダクトがあるのでこれを使っていきましょう。
リンク追加しました

2019-04-08 14:36 UTC, syossan27 commented on articles/syossan27.re
> +それでは、まずはKafka Brokerを立ち上げていきましょう。Kafka公式サイトのQuick Startを見てBrokerを立ち上げるのも一つですが、wurstmeister/kafka-dockerという便利なプロダクトがあるのでこれを使っていきましょう。
追加しました

2019-04-08 14:38 UTC, syossan27 commented on articles/syossan27.re
> +=== 作成するシステムについて
バージョン情報追加しました

2019-04-08 14:38 UTC, syossan27 commented on articles/syossan27.re
> +さて、ここでdocker-compose upで立ち上げたいところですが、その前に１点だけdocker-compose.ymlに修正を加えます。
明示的に書きました

2019-04-08 14:39 UTC, syossan27 commented on articles/syossan27.re
> +% cd ~/kafka-docker
`cd kafka-docker`に修正しました

2019-04-08 14:39 UTC, syossan27 commented on articles/syossan27.re
> +	"github.com/Shopify/sarama"
修正しました

2019-04-08 14:39 UTC, syossan27 commented on articles/syossan27.re
> +こちらはコマンド引数として渡したBrokerのアドレスに対して、「Hello World」というメッセージをtest topicに送信する簡単なものになっています。実装としてはProducerのconfigを諸々設定し、Producerを作成・メッセージの送信という流れになっており、そこまで難しくないでしょう。
参照追加しました

2019-04-08 14:40 UTC, syossan27 commented on articles/syossan27.re
> +	"github.com/Shopify/sarama"
修正しました

2019-04-08 14:40 UTC, syossan27 commented on articles/syossan27.re
> +//listnum[producer][API実装の追加][go]{
修正しました

2019-04-08 14:40 UTC, syossan27 commented on articles/syossan27.re
> +これでconsumerで確認するとhelloが表示されることでしょう。さて、ここまででAPIサーバ兼Producerの役割を持つアプリケーションは完成しました。本章の最後に今回紹介した以外のProducerでの設定項目について触れていきたいと思います。
本章→本節に修正しました

2019-04-08 14:41 UTC, syossan27 commented on articles/syossan27.re
> +これでconsumerで確認するとhelloが表示されることでしょう。さて、ここまででAPIサーバ兼Producerの役割を持つアプリケーションは完成しました。本章の最後に今回紹介した以外のProducerでの設定項目について触れていきたいと思います。
リンク追加しました

2019-04-08 14:41 UTC, syossan27 commented on articles/syossan27.re
> +基本的にはコメントで書いてあるように動くのですが、今回はSetup処理やCleanup処理は特に何もしない形で実装しております。本来であるなら、メッセージをconsumeした後によしなにデータベースへデータを挿入したりなどの処理が組み込まれますので、そういった時にHandlerでsql.DBを持ち、そこを通してデータベースのセットアップやクローズ処理をする際に使うのがベターでしょう。
装飾追加しました

2019-04-08 14:41 UTC, syossan27 commented on articles/syossan27.re
> +ここまで読んで頂きありがとうございます。分かりにくいところもあったかもしれませんが、Kafkaの様々な概念は実際に動かしてみないと分かりづらいことが多いです。是非とも個人開発や現場で使ってみてKafkaを極めていってください。また、Kafkaの情報源として最近発売された「Apache Kafka 分散メッセージングシステムの構築と活用」という本は今回扱ったような基本的な説明から、一歩進んだ実用的
リンク追加しました

2019-04-08 14:41 UTC, syossan27 commented on articles/syossan27.re
> +ここまで読んで頂きありがとうございます。分かりにくいところもあったかもしれませんが、Kafkaの様々な概念は実際に動かしてみないと分かりづらいことが多いです。是非とも個人開発や現場で使ってみてKafkaを極めていってください。また、Kafkaの情報源として最近発売された「Apache Kafka 分散メッセージングシステムの構築と活用」という本は今回扱ったような基本的な説明から、一歩進んだ実用的
追加しました

2019-04-08 14:41 UTC, syossan27 commented on articles/syossan27.re
> +//list[consumer-setting][Consumer設定一覧][]{
追加しました

2019-04-08 14:42 UTC, syossan27 commented on articles/syossan27.re
> +事前準備として適宜以下を行っておいてください。
修正しました

2019-04-08 14:42 UTC, syossan27 commented on articles/syossan27.re
> +これらが完了しましたら準備完了です。次にkafka-dockerの環境構築をしていきます。
修正しました

2019-04-08 14:42 UTC, syossan27 commented on articles/syossan27.re
> +これでtest topicを介したメッセージングの準備は出来ました。Producerを実行しているプロセスで何か文字を打ってみましょう。するとConsumerを実行しているプロセスにProducerで打った文字が表示されればKafka Brokerが正常に動いている証です。
削除しました

2019-04-08 14:42 UTC, syossan27 commented on articles/syossan27.re
> +ここからはGoの出番です。Kafkaのコマンドラインで実行していたProducerに当たる部分を実装していきます。まずはProducerのサンプルを見ていきましょう。
修正しました

2019-04-08 14:43 UTC, syossan27 commented on articles/syossan27.re
> +様々な設定がありますが、プロジェクトの規模が物凄く大きいなど特別な状況以外は特に設定することは無いものが殆どかと思われます。メッセージの量にも依るのですがKafkaのBrokerにログファイルが溜まり過ぎて、ディスク容量を食い潰して突然の死を迎えるという状況を目にしたことがあるので、筆者としてはメッセージの圧縮はやっておいた方がいいのかなと思います。
修正しました

2019-04-08 14:43 UTC, syossan27 commented on articles/syossan27.re
> +) error {
Interfaceの説明をコメントとして入れておきました

2019-04-08 14:44 UTC, syossan27 commented on articles/syossan27.re
> +背景として、LinkedIn@<fn>{linkedin}上での大量のアクティビティデータを機械学習やフィード画面に表示するためのデータパイプラインとして以下を目的として開発されました。
修正しました

2019-04-08 15:35 UTC, skanehira commented on articles/syossan27.re
> +事前準備としてDockerのインストール・Docker Composeのインストールを行っておいてください。
インストール2回は冗長なので、「事前準備としてDocker・Docker Composeのインストールを行っておいてください。」

2019-04-08 15:40 UTC, skanehira requested changes
ゴリラ分指摘修正確認しました
１件だけコメントしました

2019-04-08 15:40 UTC, skanehira commented on articles/syossan27.re
> +事前準備としてDockerのインストール・Docker Composeのインストールを行っておいてください。
インストール2回は冗長なので、「事前準備としてDocker・Docker Composeのインストールを行っておいてください。」

2019-04-08 20:22 UTC, budougumi0617 commented on articles/syossan27.re
> +また、Kafka以外の重要な要素としてZooKeeper@<fn>{zookeeper}というミドルウェアがあります。ZooKeeperは分散システムにおける設定情報やリソースの一元管理を担い、Kafkaでは主にTopicの構成（Partition数、Replicasのパスなど）の保持や、クラスタ内のブローカーのリストを保持等をしています。
一文あると全然しらない私でもわかりやすくなりました　👍 👍

2019-04-08 20:30 UTC, budougumi0617 reviewed
いくつか追加しました。

2019-04-08 20:30 UTC, budougumi0617 commented on articles/syossan27.re
> +注意点として、リプレイに必要なデータを保持するtopicの永続化に伴う適切なLog Compaction設定や、イベントをconsumeするtopic・リプライの中間データ用topicの適切な分割・設定などがあります。
お、そうすると、

> Kafkaでは主にTopicの構成（Partition数、Replicasのパスなど）

のTopicと、

> イベントをconsumeするtopic・リプライの中間データ用topic

のtopicって同じTOPICですか？表記が違うので何か違うことをさしているのかと思いました。同じTOPICなら大文字小文字をあわせて`Topic`にするとか。

2019-04-08 20:30 UTC, budougumi0617 commented on articles/syossan27.re
> +さて、ここでdocker-compose upで立ち上げたいところですが、その前に１点だけdocker-compose.ymlのKAFKA_ADVERTISED_HOST_NAMEに修正を加えます。
docker-compose upはコマンドなので、装飾したほうが良さそう。

2019-04-08 20:30 UTC, budougumi0617 commented on articles/syossan27.re
> +  // 有効にするとメッセージ送信失敗時にErrors channelに対してデータが送信される
コメントのインデントがくずれてます。うえのほうにも3ヶ所あります。

2019-04-08 20:30 UTC, budougumi0617 commented on articles/syossan27.re
> +  defer producer.Close()
ここもインデント

2019-04-08 20:30 UTC, budougumi0617 commented on articles/syossan27.re
> +    // URLクエリパラメータの取得
インデント

2019-04-08 20:30 UTC, budougumi0617 commented on articles/syossan27.re
> +//listnum[producer][API実装の追加][go]{
該当行にコメントしておきますが、コード中のインデントが崩れているのでそこも対応お願いしますー

2019-04-09 01:56 UTC, syossan27 commented on articles/syossan27.re
> +さて、ここでdocker-compose upで立ち上げたいところですが、その前に１点だけdocker-compose.ymlのKAFKA_ADVERTISED_HOST_NAMEに修正を加えます。
修正しました

2019-04-09 01:56 UTC, syossan27 commented on articles/syossan27.re
> +  // 有効にするとメッセージ送信失敗時にErrors channelに対してデータが送信される
修正しました

2019-04-09 01:56 UTC, syossan27 commented on articles/syossan27.re
> +  defer producer.Close()
修正しました

2019-04-09 01:57 UTC, syossan27 commented on articles/syossan27.re
> +    // URLクエリパラメータの取得
修正しました

2019-04-09 03:23 UTC, budougumi0617 approved these changes
私の指摘分はLGTMです！

2019-04-10 10:39 UTC, merged